//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XODB.Module.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XODB.Module.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACKUP DATABASE [XODB] TO  DISK = N&apos;{0}&apos; WITH NOFORMAT, NOINIT,  NAME = N&apos;XODB-Full Database Backup&apos;, SKIP, NOREWIND, NOUNLOAD,  STATS = 10
        ///GO.
        /// </summary>
        internal static string XODBBackup {
            get {
                return ResourceManager.GetString("XODBBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE master
        /// GO
        ///
        /// ALTER DATABASE XODB
        /// SET OFFLINE WITH ROLLBACK IMMEDIATE
        /// ALTER DATABASE XODB
        /// SET ONLINE
        /// GO
        ///
        /// USE XODB
        /// GO.
        /// </summary>
        internal static string XODBClose {
            get {
                return ResourceManager.GetString("XODBClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
        ///-- =============================================
        ///-- Author:		Andrew Grosser
        ///-- Create date: July 2012
        ///-- Description:	XODB - Xstract Open Database (Open source database for geology and mining)
        ///-- ====== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XODBSchema1 {
            get {
                return ResourceManager.GetString("XODBSchema1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/3.0/ or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
        ///-- =============================================
        ///-- Author:		Andrew Grosser
        ///-- Create date: July 2012
        ///-- Description:	XODB - Xstract Open Database (Open source database for geology and mining)
        ///-- ====== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XODBSchema1Data {
            get {
                return ResourceManager.GetString("XODBSchema1Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [XODB]
        ///GO
        ///DROP INDEX ISurvey ON dbo.X_Survey
        ///GO
        ///UPDATE X_PrivateData set Value=&apos;2&apos; where UniqueID=&apos;XODBSchemaVersion&apos;
        ///GO.
        /// </summary>
        internal static string XODBSchema2 {
            get {
                return ResourceManager.GetString("XODBSchema2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --  
        ///-- Script to Create xodb_user1 in AU-BNE-SQ-007.XODBLOCAL 
        ///-- Generated Wednesday, June 5, 2013, at 03:04 PM 
        ///--  
        ///-- Please backup AU-BNE-SQ-007.XODBLOCAL before executing this script
        ///--  
        ///-- ** Script Begin **
        ///PRINT &apos;Creating xodb_user1 User&apos;
        ///GO
        ///
        ///if not exists (select * from sys.server_principals where name = N&apos;xodb_user1&apos;)
        ///   /* For security reasons the login is created with a random password. */
        ///   CREATE LOGIN [xodb_user1] WITH PASSWORD = N&apos;-QTD.C!$M#&apos;, DEFAULT_LANGUAGE = [us_english], [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XODBSchema3 {
            get {
                return ResourceManager.GetString("XODBSchema3", resourceCulture);
            }
        }
    }
}
