//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_Address")]
    public partial class Address : XPLiteObject
    {
        Guid fAddressID;
        [Key(true)]
        public Guid AddressID
        {
            get { return fAddressID; }
            set { SetPropertyValue<Guid>("AddressID", ref fAddressID, value); }
        }
        string fAddressName;
        [Size(50)]
        public string AddressName
        {
            get { return fAddressName; }
            set { SetPropertyValue<string>("AddressName", ref fAddressName, value); }
        }
        string fStreet;
        [Size(255)]
        public string Street
        {
            get { return fStreet; }
            set { SetPropertyValue<string>("Street", ref fStreet, value); }
        }
        string fCity;
        [Size(50)]
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>("City", ref fCity, value); }
        }
        string fState;
        [Size(50)]
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>("State", ref fState, value); }
        }
        string fPostcode;
        [Size(16)]
        public string Postcode
        {
            get { return fPostcode; }
            set { SetPropertyValue<string>("Postcode", ref fPostcode, value); }
        }
        bool fIsHQ;
        public bool IsHQ
        {
            get { return fIsHQ; }
            set { SetPropertyValue<bool>("IsHQ", ref fIsHQ, value); }
        }
        bool fIsPostBox;
        public bool IsPostBox
        {
            get { return fIsPostBox; }
            set { SetPropertyValue<bool>("IsPostBox", ref fIsPostBox, value); }
        }
        int fPriority;
        public int Priority
        {
            get { return fPriority; }
            set { SetPropertyValue<int>("Priority", ref fPriority, value); }
        }
        string fPhone;
        [Size(16)]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>("Phone", ref fPhone, value); }
        }
        string fFax;
        [Size(16)]
        public string Fax
        {
            get { return fFax; }
            set { SetPropertyValue<string>("Fax", ref fFax, value); }
        }
        string fEmail;
        [Size(16)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        string fMobile;
        [Size(16)]
        public string Mobile
        {
            get { return fMobile; }
            set { SetPropertyValue<string>("Mobile", ref fMobile, value); }
        }
        Location fLocationID;
        [Association(@"AddressReferencesLocation")]
        public Location LocationID
        {
            get { return fLocationID; }
            set { SetPropertyValue<Location>("LocationID", ref fLocationID, value); }
        }
        [Association(@"CompanyAddressReferencesAddress", typeof(CompanyAddress))]
        public XPCollection<CompanyAddress> CompanyAddressCollection { get { return GetCollection<CompanyAddress>("CompanyAddressCollection"); } }
        [Association(@"ContactAddressReferencesAddress", typeof(ContactAddress))]
        public XPCollection<ContactAddress> ContactAddressCollection { get { return GetCollection<ContactAddress>("ContactAddressCollection"); } }
    }

}
