//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_AssayGroupTest")]
    public partial class AssayGroupTest : XPLiteObject
    {
        Guid fAssayGroupTestID;
        [Key(true)]
        public Guid AssayGroupTestID
        {
            get { return fAssayGroupTestID; }
            set { SetPropertyValue<Guid>("AssayGroupTestID", ref fAssayGroupTestID, value); }
        }
        AssayGroup fAssayGroupID;
        [Indexed(@"AssayTestName", Name = @"IAssayTest", Unique = true)]
        [Association(@"AssayGroupTestReferencesAssayGroup")]
        public AssayGroup AssayGroupID
        {
            get { return fAssayGroupID; }
            set { SetPropertyValue<AssayGroup>("AssayGroupID", ref fAssayGroupID, value); }
        }
        string fAssayTypeName;
        [Indexed(Name = @"iAssayType_AssayGroupTest")]
        [Size(16)]
        public string AssayTypeName
        {
            get { return fAssayTypeName; }
            set { SetPropertyValue<string>("AssayTypeName", ref fAssayTypeName, value); }
        }
        string fAssayTestName;
        [Size(16)]
        public string AssayTestName
        {
            get { return fAssayTestName; }
            set { SetPropertyValue<string>("AssayTestName", ref fAssayTestName, value); }
        }
        Parameter fParameterID;
        [Association(@"AssayGroupTestReferencesParameter")]
        public Parameter ParameterID
        {
            get { return fParameterID; }
            set { SetPropertyValue<Parameter>("ParameterID", ref fParameterID, value); }
        }
        int fAssayTestPriority;
        public int AssayTestPriority
        {
            get { return fAssayTestPriority; }
            set { SetPropertyValue<int>("AssayTestPriority", ref fAssayTestPriority, value); }
        }
        DictionaryAssayMethod fAssayMethodID;
        [Association(@"AssayGroupTestReferencesDictionaryAssayMethod")]
        public DictionaryAssayMethod AssayMethodID
        {
            get { return fAssayMethodID; }
            set { SetPropertyValue<DictionaryAssayMethod>("AssayMethodID", ref fAssayMethodID, value); }
        }
        DictionaryAssayType fAssayTypeID;
        [Association(@"AssayGroupTestReferencesDictionaryAssayType")]
        public DictionaryAssayType AssayTypeID
        {
            get { return fAssayTypeID; }
            set { SetPropertyValue<DictionaryAssayType>("AssayTypeID", ref fAssayTypeID, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>("Version", ref fVersion, value); }
        }
        Guid fVersionAntecedentID;
        public Guid VersionAntecedentID
        {
            get { return fVersionAntecedentID; }
            set { SetPropertyValue<Guid>("VersionAntecedentID", ref fVersionAntecedentID, value); }
        }
        int fVersionCertainty;
        public int VersionCertainty
        {
            get { return fVersionCertainty; }
            set { SetPropertyValue<int>("VersionCertainty", ref fVersionCertainty, value); }
        }
        Guid fVersionWorkflowInstanceID;
        public Guid VersionWorkflowInstanceID
        {
            get { return fVersionWorkflowInstanceID; }
            set { SetPropertyValue<Guid>("VersionWorkflowInstanceID", ref fVersionWorkflowInstanceID, value); }
        }
        Guid fVersionUpdatedBy;
        public Guid VersionUpdatedBy
        {
            get { return fVersionUpdatedBy; }
            set { SetPropertyValue<Guid>("VersionUpdatedBy", ref fVersionUpdatedBy, value); }
        }
        Guid fVersionDeletedBy;
        public Guid VersionDeletedBy
        {
            get { return fVersionDeletedBy; }
            set { SetPropertyValue<Guid>("VersionDeletedBy", ref fVersionDeletedBy, value); }
        }
        Guid fVersionOwnerContactID;
        public Guid VersionOwnerContactID
        {
            get { return fVersionOwnerContactID; }
            set { SetPropertyValue<Guid>("VersionOwnerContactID", ref fVersionOwnerContactID, value); }
        }
        Guid fVersionOwnerCompanyID;
        public Guid VersionOwnerCompanyID
        {
            get { return fVersionOwnerCompanyID; }
            set { SetPropertyValue<Guid>("VersionOwnerCompanyID", ref fVersionOwnerCompanyID, value); }
        }
        DateTime fVersionUpdated;
        public DateTime VersionUpdated
        {
            get { return fVersionUpdated; }
            set { SetPropertyValue<DateTime>("VersionUpdated", ref fVersionUpdated, value); }
        }
        [Association(@"AssayGroupStandardTestResultReferencesAssayGroupTest", typeof(AssayGroupStandardTestResult))]
        public XPCollection<AssayGroupStandardTestResult> AssayGroupStandardTestResults { get { return GetCollection<AssayGroupStandardTestResult>("AssayGroupStandardTestResults"); } }
        [Association(@"X_AssayGroupTestResultReferencesAssayGroupTest", typeof(AssayGroupTestResult))]
        public XPCollection<AssayGroupTestResult> X_AssayGroupTestResults { get { return GetCollection<AssayGroupTestResult>("X_AssayGroupTestResults"); } }
    }

}
