//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_AssayGroup")]
    public partial class AssayGroup : XPLiteObject
    {
        Guid fAssayGroupID;
        [Key(true)]
        public Guid AssayGroupID
        {
            get { return fAssayGroupID; }
            set { SetPropertyValue<Guid>("AssayGroupID", ref fAssayGroupID, value); }
        }
        string fAssayGroupName;
        [Size(16)]
        public string AssayGroupName
        {
            get { return fAssayGroupName; }
            set { SetPropertyValue<string>("AssayGroupName", ref fAssayGroupName, value); }
        }
        LabCompany fLabCompanyID;
        [Association(@"AssayGroupReferencesLabCompany")]
        public LabCompany LabCompanyID
        {
            get { return fLabCompanyID; }
            set { SetPropertyValue<LabCompany>("LabCompanyID", ref fLabCompanyID, value); }
        }
        DateTime fSubmitted;
        public DateTime Submitted
        {
            get { return fSubmitted; }
            set { SetPropertyValue<DateTime>("Submitted", ref fSubmitted, value); }
        }
        Contact fSubmittedContactID;
        [Association(@"AssayGroupReferencesContact")]
        public Contact SubmittedContactID
        {
            get { return fSubmittedContactID; }
            set { SetPropertyValue<Contact>("SubmittedContactID", ref fSubmittedContactID, value); }
        }
        DateTime fReceived;
        public DateTime Received
        {
            get { return fReceived; }
            set { SetPropertyValue<DateTime>("Received", ref fReceived, value); }
        }
        Contact fReceivedContactID;
        [Association(@"AssayGroupReferencesContact1")]
        public Contact ReceivedContactID
        {
            get { return fReceivedContactID; }
            set { SetPropertyValue<Contact>("ReceivedContactID", ref fReceivedContactID, value); }
        }
        DateTime fEntered;
        public DateTime Entered
        {
            get { return fEntered; }
            set { SetPropertyValue<DateTime>("Entered", ref fEntered, value); }
        }
        Contact fEnteredContactID;
        [Association(@"AssayGroupReferencesContact2")]
        public Contact EnteredContactID
        {
            get { return fEnteredContactID; }
            set { SetPropertyValue<Contact>("EnteredContactID", ref fEnteredContactID, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>("Comment", ref fComment, value); }
        }
        [Association(@"AssayGroupTestReferencesAssayGroup", typeof(AssayGroupTest))]
        public XPCollection<AssayGroupTest> AssayGroupTests { get { return GetCollection<AssayGroupTest>("AssayGroupTests"); } }
    }

}
