//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_BlockModelMetadata")]
    public partial class BlockModelMetadata : XPLiteObject
    {
        Guid fBlockModelMetadataID;
        [Key(true)]
        public Guid BlockModelMetadataID
        {
            get { return fBlockModelMetadataID; }
            set { SetPropertyValue<Guid>("BlockModelMetadataID", ref fBlockModelMetadataID, value); }
        }
        BlockModel fBlockModelID;
        [Association(@"BlockModelMetadataReferencesBlockModel")]
        public BlockModel BlockModelID
        {
            get { return fBlockModelID; }
            set { SetPropertyValue<BlockModel>("BlockModelID", ref fBlockModelID, value); }
        }
        Parameter fParameterID;
        [Association(@"BlockModelMetadataReferencesParameter")]
        public Parameter ParameterID
        {
            get { return fParameterID; }
            set { SetPropertyValue<Parameter>("ParameterID", ref fParameterID, value); }
        }
        string fBlockModelMetadataText;
        [Size(255)]
        public string BlockModelMetadataText
        {
            get { return fBlockModelMetadataText; }
            set { SetPropertyValue<string>("BlockModelMetadataText", ref fBlockModelMetadataText, value); }
        }
        decimal fBlockModelMetadataValue;
        public decimal BlockModelMetadataValue
        {
            get { return fBlockModelMetadataValue; }
            set { SetPropertyValue<decimal>("BlockModelMetadataValue", ref fBlockModelMetadataValue, value); }
        }
        bool fIsColumnData;
        public bool IsColumnData
        {
            get { return fIsColumnData; }
            set { SetPropertyValue<bool>("IsColumnData", ref fIsColumnData, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>("Version", ref fVersion, value); }
        }
        Guid fVersionAntecedentID;
        public Guid VersionAntecedentID
        {
            get { return fVersionAntecedentID; }
            set { SetPropertyValue<Guid>("VersionAntecedentID", ref fVersionAntecedentID, value); }
        }
        int fVersionCertainty;
        public int VersionCertainty
        {
            get { return fVersionCertainty; }
            set { SetPropertyValue<int>("VersionCertainty", ref fVersionCertainty, value); }
        }
        Guid fVersionWorkflowInstanceID;
        public Guid VersionWorkflowInstanceID
        {
            get { return fVersionWorkflowInstanceID; }
            set { SetPropertyValue<Guid>("VersionWorkflowInstanceID", ref fVersionWorkflowInstanceID, value); }
        }
        Guid fVersionUpdatedBy;
        public Guid VersionUpdatedBy
        {
            get { return fVersionUpdatedBy; }
            set { SetPropertyValue<Guid>("VersionUpdatedBy", ref fVersionUpdatedBy, value); }
        }
        Guid fVersionDeletedBy;
        public Guid VersionDeletedBy
        {
            get { return fVersionDeletedBy; }
            set { SetPropertyValue<Guid>("VersionDeletedBy", ref fVersionDeletedBy, value); }
        }
        Guid fVersionOwnerContactID;
        public Guid VersionOwnerContactID
        {
            get { return fVersionOwnerContactID; }
            set { SetPropertyValue<Guid>("VersionOwnerContactID", ref fVersionOwnerContactID, value); }
        }
        Guid fVersionOwnerCompanyID;
        public Guid VersionOwnerCompanyID
        {
            get { return fVersionOwnerCompanyID; }
            set { SetPropertyValue<Guid>("VersionOwnerCompanyID", ref fVersionOwnerCompanyID, value); }
        }
        DateTime fVersionUpdated;
        public DateTime VersionUpdated
        {
            get { return fVersionUpdated; }
            set { SetPropertyValue<DateTime>("VersionUpdated", ref fVersionUpdated, value); }
        }
    }

}
