//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_BlockModelBlockData")]
    public partial class BlockModelBlockData : XPLiteObject
    {
        Guid fBlockModelBlockDataID;
        [Key(true)]
        public Guid BlockModelBlockDataID
        {
            get { return fBlockModelBlockDataID; }
            set { SetPropertyValue<Guid>("BlockModelBlockDataID", ref fBlockModelBlockDataID, value); }
        }
        Parameter fParameterID;
        [Association(@"BlockModelBlockDataReferencesParameter")]
        public Parameter ParameterID
        {
            get { return fParameterID; }
            set { SetPropertyValue<Parameter>("ParameterID", ref fParameterID, value); }
        }
        BlockModelBlock fBlockModelBlockID;
        [Association(@"BlockModelBlockDataReferencesX_BlockModelBlock")]
        public BlockModelBlock BlockModelBlockID
        {
            get { return fBlockModelBlockID; }
            set { SetPropertyValue<BlockModelBlock>("BlockModelBlockID", ref fBlockModelBlockID, value); }
        }
        string fBlockModelBlockDataText;
        [Size(58)]
        public string BlockModelBlockDataText
        {
            get { return fBlockModelBlockDataText; }
            set { SetPropertyValue<string>("BlockModelBlockDataText", ref fBlockModelBlockDataText, value); }
        }
        decimal fBlockModelBlockDataValue;
        public decimal BlockModelBlockDataValue
        {
            get { return fBlockModelBlockDataValue; }
            set { SetPropertyValue<decimal>("BlockModelBlockDataValue", ref fBlockModelBlockDataValue, value); }
        }
        BlockModel fBlockModelID;
        [Association(@"BlockModelBlockDataReferencesBlockModel")]
        public BlockModel BlockModelID
        {
            get { return fBlockModelID; }
            set { SetPropertyValue<BlockModel>("BlockModelID", ref fBlockModelID, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>("Version", ref fVersion, value); }
        }
        Guid fVersionAntecedentID;
        public Guid VersionAntecedentID
        {
            get { return fVersionAntecedentID; }
            set { SetPropertyValue<Guid>("VersionAntecedentID", ref fVersionAntecedentID, value); }
        }
        int fVersionCertainty;
        public int VersionCertainty
        {
            get { return fVersionCertainty; }
            set { SetPropertyValue<int>("VersionCertainty", ref fVersionCertainty, value); }
        }
        Guid fVersionWorkflowInstanceID;
        public Guid VersionWorkflowInstanceID
        {
            get { return fVersionWorkflowInstanceID; }
            set { SetPropertyValue<Guid>("VersionWorkflowInstanceID", ref fVersionWorkflowInstanceID, value); }
        }
        Guid fVersionUpdatedBy;
        public Guid VersionUpdatedBy
        {
            get { return fVersionUpdatedBy; }
            set { SetPropertyValue<Guid>("VersionUpdatedBy", ref fVersionUpdatedBy, value); }
        }
        Guid fVersionDeletedBy;
        public Guid VersionDeletedBy
        {
            get { return fVersionDeletedBy; }
            set { SetPropertyValue<Guid>("VersionDeletedBy", ref fVersionDeletedBy, value); }
        }
        Guid fVersionOwnerContactID;
        public Guid VersionOwnerContactID
        {
            get { return fVersionOwnerContactID; }
            set { SetPropertyValue<Guid>("VersionOwnerContactID", ref fVersionOwnerContactID, value); }
        }
        Guid fVersionOwnerCompanyID;
        public Guid VersionOwnerCompanyID
        {
            get { return fVersionOwnerCompanyID; }
            set { SetPropertyValue<Guid>("VersionOwnerCompanyID", ref fVersionOwnerCompanyID, value); }
        }
        DateTime fVersionUpdated;
        public DateTime VersionUpdated
        {
            get { return fVersionUpdated; }
            set { SetPropertyValue<DateTime>("VersionUpdated", ref fVersionUpdated, value); }
        }
    }

}
