//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_Compliance")]
    public partial class Compliance : XPLiteObject
    {
        Guid fComplianceID;
        [Key(true)]
        public Guid ComplianceID
        {
            get { return fComplianceID; }
            set { SetPropertyValue<Guid>("ComplianceID", ref fComplianceID, value); }
        }
        string fComplianceName;
        [Size(120)]
        public string ComplianceName
        {
            get { return fComplianceName; }
            set { SetPropertyValue<string>("ComplianceName", ref fComplianceName, value); }
        }
        string fComplianceVersion;
        [Size(16)]
        public string ComplianceVersion
        {
            get { return fComplianceVersion; }
            set { SetPropertyValue<string>("ComplianceVersion", ref fComplianceVersion, value); }
        }
        DictionaryCountry fCountryID;
        [Size(2)]
        [Association(@"ComplianceReferencesDictionaryCountry")]
        public DictionaryCountry CountryID
        {
            get { return fCountryID; }
            set { SetPropertyValue<DictionaryCountry>("CountryID", ref fCountryID, value); }
        }
        Province fProvinceID;
        [Association(@"ComplianceReferencesProvince")]
        public Province ProvinceID
        {
            get { return fProvinceID; }
            set { SetPropertyValue<Province>("ProvinceID", ref fProvinceID, value); }
        }
        DateTime fValidFrom;
        public DateTime ValidFrom
        {
            get { return fValidFrom; }
            set { SetPropertyValue<DateTime>("ValidFrom", ref fValidFrom, value); }
        }
        DateTime fExpiry;
        public DateTime Expiry
        {
            get { return fExpiry; }
            set { SetPropertyValue<DateTime>("Expiry", ref fExpiry, value); }
        }
        Company fAuthorityCompanyID;
        [Association(@"ComplianceReferencesCompany")]
        public Company AuthorityCompanyID
        {
            get { return fAuthorityCompanyID; }
            set { SetPropertyValue<Company>("AuthorityCompanyID", ref fAuthorityCompanyID, value); }
        }
        Contact fMaintainedBy;
        [Association(@"ComplianceReferencesContact")]
        public Contact MaintainedBy
        {
            get { return fMaintainedBy; }
            set { SetPropertyValue<Contact>("MaintainedBy", ref fMaintainedBy, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fComplianceForm;
        [Size(SizeAttribute.Unlimited)]
        public string ComplianceForm
        {
            get { return fComplianceForm; }
            set { SetPropertyValue<string>("ComplianceForm", ref fComplianceForm, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>("Version", ref fVersion, value); }
        }
        Guid fVersionAntecedentID;
        public Guid VersionAntecedentID
        {
            get { return fVersionAntecedentID; }
            set { SetPropertyValue<Guid>("VersionAntecedentID", ref fVersionAntecedentID, value); }
        }
        int fVersionCertainty;
        public int VersionCertainty
        {
            get { return fVersionCertainty; }
            set { SetPropertyValue<int>("VersionCertainty", ref fVersionCertainty, value); }
        }
        Guid fVersionWorkflowInstanceID;
        public Guid VersionWorkflowInstanceID
        {
            get { return fVersionWorkflowInstanceID; }
            set { SetPropertyValue<Guid>("VersionWorkflowInstanceID", ref fVersionWorkflowInstanceID, value); }
        }
        Guid fVersionUpdatedBy;
        public Guid VersionUpdatedBy
        {
            get { return fVersionUpdatedBy; }
            set { SetPropertyValue<Guid>("VersionUpdatedBy", ref fVersionUpdatedBy, value); }
        }
        Guid fVersionDeletedBy;
        public Guid VersionDeletedBy
        {
            get { return fVersionDeletedBy; }
            set { SetPropertyValue<Guid>("VersionDeletedBy", ref fVersionDeletedBy, value); }
        }
        Guid fVersionOwnerContactID;
        public Guid VersionOwnerContactID
        {
            get { return fVersionOwnerContactID; }
            set { SetPropertyValue<Guid>("VersionOwnerContactID", ref fVersionOwnerContactID, value); }
        }
        Guid fVersionOwnerCompanyID;
        public Guid VersionOwnerCompanyID
        {
            get { return fVersionOwnerCompanyID; }
            set { SetPropertyValue<Guid>("VersionOwnerCompanyID", ref fVersionOwnerCompanyID, value); }
        }
        DateTime fVersionUpdated;
        public DateTime VersionUpdated
        {
            get { return fVersionUpdated; }
            set { SetPropertyValue<DateTime>("VersionUpdated", ref fVersionUpdated, value); }
        }
        [Association(@"ComplianceWorkTypeReferencesCompliance", typeof(ComplianceWorkType))]
        public XPCollection<ComplianceWorkType> ComplianceWorkTypes { get { return GetCollection<ComplianceWorkType>("ComplianceWorkTypes"); } }
    }

}
