//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_CompanyAddress")]
    public partial class CompanyAddress : XPLiteObject
    {
        Guid fCompanyAddressID;
        [Key(true)]
        public Guid CompanyAddressID
        {
            get { return fCompanyAddressID; }
            set { SetPropertyValue<Guid>("CompanyAddressID", ref fCompanyAddressID, value); }
        }
        Company fCompanyID;
        [Association(@"CompanyAddressReferencesCompany")]
        public Company CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<Company>("CompanyID", ref fCompanyID, value); }
        }
        Address fAddressID;
        [Association(@"CompanyAddressReferencesAddress")]
        public Address AddressID
        {
            get { return fAddressID; }
            set { SetPropertyValue<Address>("AddressID", ref fAddressID, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>("Version", ref fVersion, value); }
        }
        Guid fVersionAntecedentID;
        public Guid VersionAntecedentID
        {
            get { return fVersionAntecedentID; }
            set { SetPropertyValue<Guid>("VersionAntecedentID", ref fVersionAntecedentID, value); }
        }
        int fVersionCertainty;
        public int VersionCertainty
        {
            get { return fVersionCertainty; }
            set { SetPropertyValue<int>("VersionCertainty", ref fVersionCertainty, value); }
        }
        Guid fVersionWorkflowInstanceID;
        public Guid VersionWorkflowInstanceID
        {
            get { return fVersionWorkflowInstanceID; }
            set { SetPropertyValue<Guid>("VersionWorkflowInstanceID", ref fVersionWorkflowInstanceID, value); }
        }
        Guid fVersionUpdatedBy;
        public Guid VersionUpdatedBy
        {
            get { return fVersionUpdatedBy; }
            set { SetPropertyValue<Guid>("VersionUpdatedBy", ref fVersionUpdatedBy, value); }
        }
        Guid fVersionDeletedBy;
        public Guid VersionDeletedBy
        {
            get { return fVersionDeletedBy; }
            set { SetPropertyValue<Guid>("VersionDeletedBy", ref fVersionDeletedBy, value); }
        }
        Guid fVersionOwnerContactID;
        public Guid VersionOwnerContactID
        {
            get { return fVersionOwnerContactID; }
            set { SetPropertyValue<Guid>("VersionOwnerContactID", ref fVersionOwnerContactID, value); }
        }
        Guid fVersionOwnerCompanyID;
        public Guid VersionOwnerCompanyID
        {
            get { return fVersionOwnerCompanyID; }
            set { SetPropertyValue<Guid>("VersionOwnerCompanyID", ref fVersionOwnerCompanyID, value); }
        }
        DateTime fVersionUpdated;
        public DateTime VersionUpdated
        {
            get { return fVersionUpdated; }
            set { SetPropertyValue<DateTime>("VersionUpdated", ref fVersionUpdated, value); }
        }
        [Association(@"InvoiceReferencesCompanyAddress", typeof(Invoice))]
        public XPCollection<Invoice> Invoices { get { return GetCollection<Invoice>("Invoices"); } }
        [Association(@"InvoiceReferencesCompanyAddress1", typeof(Invoice))]
        public XPCollection<Invoice> Invoices1 { get { return GetCollection<Invoice>("Invoices1"); } }
        [Association(@"DeliveryAdviceReferencesCompanyAddress", typeof(DeliveryAdvice))]
        public XPCollection<DeliveryAdvice> DeliveryAdvices { get { return GetCollection<DeliveryAdvice>("DeliveryAdvices"); } }
        [Association(@"DeliveryAdviceReferencesCompanyAddress1", typeof(DeliveryAdvice))]
        public XPCollection<DeliveryAdvice> DeliveryAdvices1 { get { return GetCollection<DeliveryAdvice>("DeliveryAdvices1"); } }
    }

}
