//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_Desurvey")]
    public partial class Desurvey : XPLiteObject
    {
        Guid fDesurveyID;
        [Key(true)]
        public Guid DesurveyID
        {
            get { return fDesurveyID; }
            set { SetPropertyValue<Guid>("DesurveyID", ref fDesurveyID, value); }
        }
        Survey fSurveyID;
        [Association(@"DesurveyReferencesSurvey")]
        public Survey SurveyID
        {
            get { return fSurveyID; }
            set { SetPropertyValue<Survey>("SurveyID", ref fSurveyID, value); }
        }
        DictionaryDesurveyAlgorithmType fDesurveyAlgorithmTypeID;
        [Association(@"DesurveyReferencesDictionaryDesurveyAlgorithmType")]
        public DictionaryDesurveyAlgorithmType DesurveyAlgorithmTypeID
        {
            get { return fDesurveyAlgorithmTypeID; }
            set { SetPropertyValue<DictionaryDesurveyAlgorithmType>("DesurveyAlgorithmTypeID", ref fDesurveyAlgorithmTypeID, value); }
        }
        [Association(@"CompositeReferencesDesurvey", typeof(Composite))]
        public XPCollection<Composite> Composites { get { return GetCollection<Composite>("Composites"); } }
    }

}
