//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryCommodity")]
    public partial class DictionaryCommodity : XPLiteObject
    {
        Guid fCommodityID;
        [Key(true)]
        public Guid CommodityID
        {
            get { return fCommodityID; }
            set { SetPropertyValue<Guid>("CommodityID", ref fCommodityID, value); }
        }
        string fStandardCommodityName;
        [Indexed(Name = @"IDictionaryCommodity", Unique = true)]
        [Size(30)]
        public string StandardCommodityName
        {
            get { return fStandardCommodityName; }
            set { SetPropertyValue<string>("StandardCommodityName", ref fStandardCommodityName, value); }
        }
        string fCoalCommodityName;
        [Size(30)]
        public string CoalCommodityName
        {
            get { return fCoalCommodityName; }
            set { SetPropertyValue<string>("CoalCommodityName", ref fCoalCommodityName, value); }
        }
        string fGoldCommodityName;
        [Size(30)]
        public string GoldCommodityName
        {
            get { return fGoldCommodityName; }
            set { SetPropertyValue<string>("GoldCommodityName", ref fGoldCommodityName, value); }
        }
        string fCustomCommodityName;
        [Size(30)]
        public string CustomCommodityName
        {
            get { return fCustomCommodityName; }
            set { SetPropertyValue<string>("CustomCommodityName", ref fCustomCommodityName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fFullDescription;
        [Size(SizeAttribute.Unlimited)]
        public string FullDescription
        {
            get { return fFullDescription; }
            set { SetPropertyValue<string>("FullDescription", ref fFullDescription, value); }
        }
        System.Drawing.Image fThumbnail;
        [Size(SizeAttribute.Unlimited)]
        [ValueConverter(typeof(DevExpress.Xpo.Metadata.ImageValueConverter))]
        public System.Drawing.Image Thumbnail
        {
            get { return fThumbnail; }
            set { SetPropertyValue<System.Drawing.Image>("Thumbnail", ref fThumbnail, value); }
        }
        FileData fOriginalFileDataID;
        [Association(@"DictionaryCommodityReferencesFileData")]
        public FileData OriginalFileDataID
        {
            get { return fOriginalFileDataID; }
            set { SetPropertyValue<FileData>("OriginalFileDataID", ref fOriginalFileDataID, value); }
        }
        [Association(@"ProspectusProjectCommodityReferencesDictionaryCommodity", typeof(ProspectusProjectCommodity))]
        public XPCollection<ProspectusProjectCommodity> ProspectusProjectCommodities { get { return GetCollection<ProspectusProjectCommodity>("ProspectusProjectCommodities"); } }
        [Association(@"TenementCommodityReferencesDictionaryCommodity", typeof(TenementCommodity))]
        public XPCollection<TenementCommodity> TenementCommodities { get { return GetCollection<TenementCommodity>("TenementCommodities"); } }
    }

}
