//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryHoleStatus")]
    public partial class DictionaryHoleStatus : XPLiteObject
    {
        Guid fHoleStatusID;
        [Key(true)]
        public Guid HoleStatusID
        {
            get { return fHoleStatusID; }
            set { SetPropertyValue<Guid>("HoleStatusID", ref fHoleStatusID, value); }
        }
        string fStandardHoleStatusName;
        [Indexed(Name = @"IDictionaryHoleStatus", Unique = true)]
        [Size(16)]
        public string StandardHoleStatusName
        {
            get { return fStandardHoleStatusName; }
            set { SetPropertyValue<string>("StandardHoleStatusName", ref fStandardHoleStatusName, value); }
        }
        string fCoalHoleStatusName;
        [Size(16)]
        public string CoalHoleStatusName
        {
            get { return fCoalHoleStatusName; }
            set { SetPropertyValue<string>("CoalHoleStatusName", ref fCoalHoleStatusName, value); }
        }
        string fGoldHoleStatusName;
        [Size(16)]
        public string GoldHoleStatusName
        {
            get { return fGoldHoleStatusName; }
            set { SetPropertyValue<string>("GoldHoleStatusName", ref fGoldHoleStatusName, value); }
        }
        string fCustomHoleStatusName;
        [Size(16)]
        public string CustomHoleStatusName
        {
            get { return fCustomHoleStatusName; }
            set { SetPropertyValue<string>("CustomHoleStatusName", ref fCustomHoleStatusName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        [Association(@"HeaderReferencesDictionaryHoleStatus", typeof(Header))]
        public XPCollection<Header> Headers { get { return GetCollection<Header>("Headers"); } }
    }

}
