//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"Q_DictionaryEventType")]
    public partial class DictionaryEventType : XPLiteObject
    {
        Guid fEventTypeID;
        [Key(true)]
        public Guid EventTypeID
        {
            get { return fEventTypeID; }
            set { SetPropertyValue<Guid>("EventTypeID", ref fEventTypeID, value); }
        }
        string fStandardEventTypeName;
        [Size(60)]
        public string StandardEventTypeName
        {
            get { return fStandardEventTypeName; }
            set { SetPropertyValue<string>("StandardEventTypeName", ref fStandardEventTypeName, value); }
        }
        string fCustomEventTypeName;
        [Size(60)]
        public string CustomEventTypeName
        {
            get { return fCustomEventTypeName; }
            set { SetPropertyValue<string>("CustomEventTypeName", ref fCustomEventTypeName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        [Association(@"WorkflowScheduleReferencesQ_DictionaryEventType", typeof(WorkflowSchedule))]
        public XPCollection<WorkflowSchedule> WorkflowSchedules { get { return GetCollection<WorkflowSchedule>("WorkflowSchedules"); } }
    }

}
