//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryEstimatedStrength")]
    public partial class DictionaryEstimatedStrength : XPLiteObject
    {
        Guid fEstimatedStrengthID;
        [Key(true)]
        public Guid EstimatedStrengthID
        {
            get { return fEstimatedStrengthID; }
            set { SetPropertyValue<Guid>("EstimatedStrengthID", ref fEstimatedStrengthID, value); }
        }
        string fStandardEstimatedStrengthName;
        [Indexed(Name = @"IDictionaryEstimatedStrength", Unique = true)]
        [Size(16)]
        public string StandardEstimatedStrengthName
        {
            get { return fStandardEstimatedStrengthName; }
            set { SetPropertyValue<string>("StandardEstimatedStrengthName", ref fStandardEstimatedStrengthName, value); }
        }
        string fCoalEstimatedStrengthName;
        [Size(16)]
        public string CoalEstimatedStrengthName
        {
            get { return fCoalEstimatedStrengthName; }
            set { SetPropertyValue<string>("CoalEstimatedStrengthName", ref fCoalEstimatedStrengthName, value); }
        }
        string fGoldEstimatedStrengthName;
        [Size(16)]
        public string GoldEstimatedStrengthName
        {
            get { return fGoldEstimatedStrengthName; }
            set { SetPropertyValue<string>("GoldEstimatedStrengthName", ref fGoldEstimatedStrengthName, value); }
        }
        string fCustomEstimatedStrengthName;
        [Size(16)]
        public string CustomEstimatedStrengthName
        {
            get { return fCustomEstimatedStrengthName; }
            set { SetPropertyValue<string>("CustomEstimatedStrengthName", ref fCustomEstimatedStrengthName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fFullDescription;
        [Size(SizeAttribute.Unlimited)]
        public string FullDescription
        {
            get { return fFullDescription; }
            set { SetPropertyValue<string>("FullDescription", ref fFullDescription, value); }
        }
        System.Drawing.Image fThumbnail;
        [Size(SizeAttribute.Unlimited)]
        [ValueConverter(typeof(DevExpress.Xpo.Metadata.ImageValueConverter))]
        public System.Drawing.Image Thumbnail
        {
            get { return fThumbnail; }
            set { SetPropertyValue<System.Drawing.Image>("Thumbnail", ref fThumbnail, value); }
        }
        FileData fOriginalFileDataID;
        [Association(@"DictionaryEstimatedStrengthReferencesFileData")]
        public FileData OriginalFileDataID
        {
            get { return fOriginalFileDataID; }
            set { SetPropertyValue<FileData>("OriginalFileDataID", ref fOriginalFileDataID, value); }
        }
        [Association(@"LithologyReferencesDictionaryEstimatedStrength", typeof(Lithology))]
        public XPCollection<Lithology> Lithologies { get { return GetCollection<Lithology>("Lithologies"); } }
        [Association(@"X_DefectReferencesDictionaryEstimatedStrength1", typeof(Defect))]
        public XPCollection<Defect> X_Defects1 { get { return GetCollection<Defect>("X_Defects1"); } }
        [Association(@"X_DefectReferencesDictionaryEstimatedStrength", typeof(Defect))]
        public XPCollection<Defect> X_Defects { get { return GetCollection<Defect>("X_Defects"); } }
    }

}
