//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"E_DictionaryTax")]
    public partial class DictionaryTax : XPLiteObject
    {
        Guid fTaxID;
        [Key(true)]
        public Guid TaxID
        {
            get { return fTaxID; }
            set { SetPropertyValue<Guid>("TaxID", ref fTaxID, value); }
        }
        string fTaxName;
        [Size(60)]
        public string TaxName
        {
            get { return fTaxName; }
            set { SetPropertyValue<string>("TaxName", ref fTaxName, value); }
        }
        decimal fTaxRate;
        public decimal TaxRate
        {
            get { return fTaxRate; }
            set { SetPropertyValue<decimal>("TaxRate", ref fTaxRate, value); }
        }
        DictionaryUnit fTaxRateUnitID;
        [Association(@"E_DictionaryTaxReferencesDictionaryUnit")]
        public DictionaryUnit TaxRateUnitID
        {
            get { return fTaxRateUnitID; }
            set { SetPropertyValue<DictionaryUnit>("TaxRateUnitID", ref fTaxRateUnitID, value); }
        }
        DictionaryCountry fCountryID;
        [Size(2)]
        [Association(@"E_DictionaryTaxReferencesDictionaryCountry")]
        public DictionaryCountry CountryID
        {
            get { return fCountryID; }
            set { SetPropertyValue<DictionaryCountry>("CountryID", ref fCountryID, value); }
        }
        DictionaryCountryState fCountryStateID;
        [Association(@"E_DictionaryTaxReferencesDictionaryCountryState")]
        public DictionaryCountryState CountryStateID
        {
            get { return fCountryStateID; }
            set { SetPropertyValue<DictionaryCountryState>("CountryStateID", ref fCountryStateID, value); }
        }
        Province fProvinceID;
        [Association(@"E_DictionaryTaxReferencesProvince")]
        public Province ProvinceID
        {
            get { return fProvinceID; }
            set { SetPropertyValue<Province>("ProvinceID", ref fProvinceID, value); }
        }
        DateTime fApplicableFrom;
        public DateTime ApplicableFrom
        {
            get { return fApplicableFrom; }
            set { SetPropertyValue<DateTime>("ApplicableFrom", ref fApplicableFrom, value); }
        }
        DateTime fApplicableUntil;
        public DateTime ApplicableUntil
        {
            get { return fApplicableUntil; }
            set { SetPropertyValue<DateTime>("ApplicableUntil", ref fApplicableUntil, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>("Version", ref fVersion, value); }
        }
        Guid fVersionAntecedentID;
        public Guid VersionAntecedentID
        {
            get { return fVersionAntecedentID; }
            set { SetPropertyValue<Guid>("VersionAntecedentID", ref fVersionAntecedentID, value); }
        }
        int fVersionCertainty;
        public int VersionCertainty
        {
            get { return fVersionCertainty; }
            set { SetPropertyValue<int>("VersionCertainty", ref fVersionCertainty, value); }
        }
        Guid fVersionWorkflowInstanceID;
        public Guid VersionWorkflowInstanceID
        {
            get { return fVersionWorkflowInstanceID; }
            set { SetPropertyValue<Guid>("VersionWorkflowInstanceID", ref fVersionWorkflowInstanceID, value); }
        }
        Guid fVersionUpdatedBy;
        public Guid VersionUpdatedBy
        {
            get { return fVersionUpdatedBy; }
            set { SetPropertyValue<Guid>("VersionUpdatedBy", ref fVersionUpdatedBy, value); }
        }
        Guid fVersionDeletedBy;
        public Guid VersionDeletedBy
        {
            get { return fVersionDeletedBy; }
            set { SetPropertyValue<Guid>("VersionDeletedBy", ref fVersionDeletedBy, value); }
        }
        Guid fVersionOwnerContactID;
        public Guid VersionOwnerContactID
        {
            get { return fVersionOwnerContactID; }
            set { SetPropertyValue<Guid>("VersionOwnerContactID", ref fVersionOwnerContactID, value); }
        }
        Guid fVersionOwnerCompanyID;
        public Guid VersionOwnerCompanyID
        {
            get { return fVersionOwnerCompanyID; }
            set { SetPropertyValue<Guid>("VersionOwnerCompanyID", ref fVersionOwnerCompanyID, value); }
        }
        DateTime fVersionUpdated;
        public DateTime VersionUpdated
        {
            get { return fVersionUpdated; }
            set { SetPropertyValue<DateTime>("VersionUpdated", ref fVersionUpdated, value); }
        }
        [Association(@"E_SupplyItemReferencesE_DictionaryTax", typeof(SupplyItem))]
        public XPCollection<SupplyItem> E_SupplyItems { get { return GetCollection<SupplyItem>("E_SupplyItems"); } }
        [Association(@"E_InvoiceLineReferencesE_DictionaryTax", typeof(InvoiceLine))]
        public XPCollection<InvoiceLine> E_InvoiceLines { get { return GetCollection<InvoiceLine>("E_InvoiceLines"); } }
    }

}
