//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryCountry")]
    public partial class DictionaryCountry : XPLiteObject
    {
        string fCountryID;
        [Key]
        [Size(2)]
        public string CountryID
        {
            get { return fCountryID; }
            set { SetPropertyValue<string>("CountryID", ref fCountryID, value); }
        }
        string fStandardCountryName;
        [Size(40)]
        public string StandardCountryName
        {
            get { return fStandardCountryName; }
            set { SetPropertyValue<string>("StandardCountryName", ref fStandardCountryName, value); }
        }
        string fCoalCountryName;
        [Size(40)]
        public string CoalCountryName
        {
            get { return fCoalCountryName; }
            set { SetPropertyValue<string>("CoalCountryName", ref fCoalCountryName, value); }
        }
        string fGoldCountryName;
        [Size(40)]
        public string GoldCountryName
        {
            get { return fGoldCountryName; }
            set { SetPropertyValue<string>("GoldCountryName", ref fGoldCountryName, value); }
        }
        string fCustomCountryName;
        [Size(40)]
        public string CustomCountryName
        {
            get { return fCustomCountryName; }
            set { SetPropertyValue<string>("CustomCountryName", ref fCustomCountryName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        [Association(@"CompanyReferencesDictionaryCountry", typeof(Company))]
        public XPCollection<Company> Companys { get { return GetCollection<Company>("Companys"); } }
        [Association(@"ContactReferencesDictionaryCountry", typeof(Contact))]
        public XPCollection<Contact> Contacts { get { return GetCollection<Contact>("Contacts"); } }
        [Association(@"DictionaryCountryStateReferencesDictionaryCountry", typeof(DictionaryCountryState))]
        public XPCollection<DictionaryCountryState> DictionaryCountryStates { get { return GetCollection<DictionaryCountryState>("DictionaryCountryStates"); } }
        [Association(@"LocationReferencesDictionaryCountry", typeof(Location))]
        public XPCollection<Location> Locations { get { return GetCollection<Location>("Locations"); } }
        [Association(@"ProspectusProjectReferencesDictionaryCountry", typeof(ProspectusProject))]
        public XPCollection<ProspectusProject> ProspectusProjects { get { return GetCollection<ProspectusProject>("ProspectusProjects"); } }
        [Association(@"ProvinceReferencesDictionaryCountry", typeof(Province))]
        public XPCollection<Province> Provinces { get { return GetCollection<Province>("Provinces"); } }
        [Association(@"TenementReferencesDictionaryCountry", typeof(Tenement))]
        public XPCollection<Tenement> Tenements { get { return GetCollection<Tenement>("Tenements"); } }
    }

}
