//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryUnit")]
    public partial class DictionaryUnit : XPLiteObject
    {
        Guid fUnitID;
        [Key(true)]
        public Guid UnitID
        {
            get { return fUnitID; }
            set { SetPropertyValue<Guid>("UnitID", ref fUnitID, value); }
        }
        string fStandardUnitName;
        [Indexed(Name = @"IDictionaryUnit", Unique = true)]
        [Size(16)]
        public string StandardUnitName
        {
            get { return fStandardUnitName; }
            set { SetPropertyValue<string>("StandardUnitName", ref fStandardUnitName, value); }
        }
        string fCoalUnitName;
        [Size(16)]
        public string CoalUnitName
        {
            get { return fCoalUnitName; }
            set { SetPropertyValue<string>("CoalUnitName", ref fCoalUnitName, value); }
        }
        string fGoldUnitName;
        [Size(16)]
        public string GoldUnitName
        {
            get { return fGoldUnitName; }
            set { SetPropertyValue<string>("GoldUnitName", ref fGoldUnitName, value); }
        }
        string fCustomUnitName;
        [Size(16)]
        public string CustomUnitName
        {
            get { return fCustomUnitName; }
            set { SetPropertyValue<string>("CustomUnitName", ref fCustomUnitName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        bool fStrictlySI;
        public bool StrictlySI
        {
            get { return fStrictlySI; }
            set { SetPropertyValue<bool>("StrictlySI", ref fStrictlySI, value); }
        }
        Guid fEquivalentUnit;
        public Guid EquivalentUnit
        {
            get { return fEquivalentUnit; }
            set { SetPropertyValue<Guid>("EquivalentUnit", ref fEquivalentUnit, value); }
        }
        decimal fEquivalentMultiplier;
        public decimal EquivalentMultiplier
        {
            get { return fEquivalentMultiplier; }
            set { SetPropertyValue<decimal>("EquivalentMultiplier", ref fEquivalentMultiplier, value); }
        }
        string fFullDescription;
        [Size(SizeAttribute.Unlimited)]
        public string FullDescription
        {
            get { return fFullDescription; }
            set { SetPropertyValue<string>("FullDescription", ref fFullDescription, value); }
        }
        System.Drawing.Image fThumbnail;
        [Size(SizeAttribute.Unlimited)]
        [ValueConverter(typeof(DevExpress.Xpo.Metadata.ImageValueConverter))]
        public System.Drawing.Image Thumbnail
        {
            get { return fThumbnail; }
            set { SetPropertyValue<System.Drawing.Image>("Thumbnail", ref fThumbnail, value); }
        }
        FileData fOriginalFileDataID;
        [Association(@"DictionaryUnitReferencesFileData")]
        public FileData OriginalFileDataID
        {
            get { return fOriginalFileDataID; }
            set { SetPropertyValue<FileData>("OriginalFileDataID", ref fOriginalFileDataID, value); }
        }
        DictionaryUnitType fUnitTypeID;
        [Association(@"DictionaryUnitReferencesX_DictionaryUnitType")]
        public DictionaryUnitType UnitTypeID
        {
            get { return fUnitTypeID; }
            set { SetPropertyValue<DictionaryUnitType>("UnitTypeID", ref fUnitTypeID, value); }
        }
        [Association(@"ParameterReferencesDictionaryUnit", typeof(Parameter))]
        public XPCollection<Parameter> Parameters { get { return GetCollection<Parameter>("Parameters"); } }
        [Association(@"ProjectDeliverableReferencesDictionaryUnit", typeof(ProjectDeliverable))]
        public XPCollection<ProjectDeliverable> ProjectDeliverables { get { return GetCollection<ProjectDeliverable>("ProjectDeliverables"); } }
        [Association(@"GeophysicsReferencesDictionaryUnit", typeof(Geophysics))]
        public XPCollection<Geophysics> GeophysicsCollection { get { return GetCollection<Geophysics>("GeophysicsCollection"); } }
        [Association(@"DictionaryPartKitItemReferencesDictionaryUnit", typeof(DictionaryPartKitItem))]
        public XPCollection<DictionaryPartKitItem> DictionaryPartKitItems { get { return GetCollection<DictionaryPartKitItem>("DictionaryPartKitItems"); } }
        [Association(@"ModelScheduleCycleReferencesDictionaryUnit", typeof(ModelScheduleCycle))]
        public XPCollection<ModelScheduleCycle> ModelScheduleCycles { get { return GetCollection<ModelScheduleCycle>("ModelScheduleCycles"); } }
        [Association(@"ModelWarrantyReferencesDictionaryUnit", typeof(ModelWarranty))]
        public XPCollection<ModelWarranty> ModelWarranties { get { return GetCollection<ModelWarranty>("ModelWarranties"); } }
        [Association(@"SupplierPartReferencesDictionaryUnit", typeof(SupplierPart))]
        public XPCollection<SupplierPart> SupplierParts { get { return GetCollection<SupplierPart>("SupplierParts"); } }
        [Association(@"SupplierPartReferencesDictionaryUnit1", typeof(SupplierPart))]
        public XPCollection<SupplierPart> SupplierParts1 { get { return GetCollection<SupplierPart>("SupplierParts1"); } }
        [Association(@"TaskReferencesDictionaryUnit", typeof(Task))]
        public XPCollection<Task> Tasks { get { return GetCollection<Task>("Tasks"); } }
        [Association(@"ProjectPlanTaskPartReferencesDictionaryUnit", typeof(ProjectPlanTaskPart))]
        public XPCollection<ProjectPlanTaskPart> ProjectPlanTaskParts { get { return GetCollection<ProjectPlanTaskPart>("ProjectPlanTaskParts"); } }
        [Association(@"AssetWarrantyReferencesDictionaryUnit", typeof(AssetWarranty))]
        public XPCollection<AssetWarranty> AssetWarranties { get { return GetCollection<AssetWarranty>("AssetWarranties"); } }
        [Association(@"ModelProcedureTaskReferencesDictionaryUnit", typeof(ModelProcedureTask))]
        public XPCollection<ModelProcedureTask> ModelProcedureTasks { get { return GetCollection<ModelProcedureTask>("ModelProcedureTasks"); } }
        [Association(@"DictionaryTaxReferencesDictionaryUnit", typeof(DictionaryTax))]
        public XPCollection<DictionaryTax> DictionaryTaxs { get { return GetCollection<DictionaryTax>("DictionaryTaxs"); } }
        [Association(@"CostEstimateModelReferencesDictionaryUnit", typeof(CostEstimateModel))]
        public XPCollection<CostEstimateModel> CostEstimateModels { get { return GetCollection<CostEstimateModel>("CostEstimateModels"); } }
        [Association(@"CostEstimateModelReferencesDictionaryUnit1", typeof(CostEstimateModel))]
        public XPCollection<CostEstimateModel> CostEstimateModels1 { get { return GetCollection<CostEstimateModel>("CostEstimateModels1"); } }
        [Association(@"WarehouseModelSupplierReferencesDictionaryUnit", typeof(WarehouseModelSupplier))]
        public XPCollection<WarehouseModelSupplier> WarehouseModelSuppliers { get { return GetCollection<WarehouseModelSupplier>("WarehouseModelSuppliers"); } }
        [Association(@"DictionaryCharacteristicReferencesDictionaryUnit", typeof(DictionaryCharacteristic))]
        public XPCollection<DictionaryCharacteristic> DictionaryCharacteristics { get { return GetCollection<DictionaryCharacteristic>("DictionaryCharacteristics"); } }
        [Association(@"ContractConditionReferencesDictionaryUnit", typeof(ContractCondition))]
        public XPCollection<ContractCondition> ContractConditions { get { return GetCollection<ContractCondition>("ContractConditions"); } }
        [Association(@"ProjectPlanTaskModelReferencesDictionaryUnit", typeof(ProjectPlanTaskModel))]
        public XPCollection<ProjectPlanTaskModel> ProjectPlanTaskModels { get { return GetCollection<ProjectPlanTaskModel>("ProjectPlanTaskModels"); } }
        [Association(@"SupplierModelReferencesDictionaryUnit", typeof(SupplierModel))]
        public XPCollection<SupplierModel> SupplierModels { get { return GetCollection<SupplierModel>("SupplierModels"); } }
        [Association(@"SupplierModelReferencesDictionaryUnit1", typeof(SupplierModel))]
        public XPCollection<SupplierModel> SupplierModels1 { get { return GetCollection<SupplierModel>("SupplierModels1"); } }
        [Association(@"WarehousePartSupplierReferencesDictionaryUnit", typeof(WarehousePartSupplier))]
        public XPCollection<WarehousePartSupplier> WarehousePartSuppliers { get { return GetCollection<WarehousePartSupplier>("WarehousePartSuppliers"); } }
        [Association(@"DictionaryModelReferencesDictionaryUnit", typeof(DictionaryModel))]
        public XPCollection<DictionaryModel> DictionaryModels { get { return GetCollection<DictionaryModel>("DictionaryModels"); } }
        [Association(@"SupplyItemReferencesDictionaryUnit", typeof(SupplyItem))]
        public XPCollection<SupplyItem> SupplyItems { get { return GetCollection<SupplyItem>("SupplyItems"); } }
        [Association(@"SupplyItemReferencesDictionaryUnit1", typeof(SupplyItem))]
        public XPCollection<SupplyItem> SupplyItems1 { get { return GetCollection<SupplyItem>("SupplyItems1"); } }
        [Association(@"SupplyItemReferencesDictionaryUnit2", typeof(SupplyItem))]
        public XPCollection<SupplyItem> SupplyItems2 { get { return GetCollection<SupplyItem>("SupplyItems2"); } }
        [Association(@"AccountDiscountReferencesDictionaryUnit", typeof(AccountDiscount))]
        public XPCollection<AccountDiscount> AccountDiscounts { get { return GetCollection<AccountDiscount>("AccountDiscounts"); } }
        [Association(@"DictionaryPartReferencesDictionaryUnit", typeof(DictionaryPart))]
        public XPCollection<DictionaryPart> DictionaryParts { get { return GetCollection<DictionaryPart>("DictionaryParts"); } }
    }

}
