//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"Q_DictionaryProcedure")]
    public partial class DictionaryProcedure : XPLiteObject
    {
        Guid fProcedureID;
        [Key(true)]
        public Guid ProcedureID
        {
            get { return fProcedureID; }
            set { SetPropertyValue<Guid>("ProcedureID", ref fProcedureID, value); }
        }
        string fStandardProcedureName;
        [Size(60)]
        public string StandardProcedureName
        {
            get { return fStandardProcedureName; }
            set { SetPropertyValue<string>("StandardProcedureName", ref fStandardProcedureName, value); }
        }
        string fCustomProcedureName;
        [Size(60)]
        public string CustomProcedureName
        {
            get { return fCustomProcedureName; }
            set { SetPropertyValue<string>("CustomProcedureName", ref fCustomProcedureName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        [Association(@"Q_ModelProcedureReferencesQ_DictionaryProcedure", typeof(ModelProcedure))]
        public XPCollection<ModelProcedure> Q_ModelProcedures { get { return GetCollection<ModelProcedure>("Q_ModelProcedures"); } }
    }

}
