//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryHue")]
    public partial class DictionaryHue : XPLiteObject
    {
        Guid fHueID;
        [Key(true)]
        public Guid HueID
        {
            get { return fHueID; }
            set { SetPropertyValue<Guid>("HueID", ref fHueID, value); }
        }
        string fStandardHueName;
        [Indexed(Name = @"IDictionaryHue", Unique = true)]
        [Size(16)]
        public string StandardHueName
        {
            get { return fStandardHueName; }
            set { SetPropertyValue<string>("StandardHueName", ref fStandardHueName, value); }
        }
        string fCoalHueName;
        [Size(16)]
        public string CoalHueName
        {
            get { return fCoalHueName; }
            set { SetPropertyValue<string>("CoalHueName", ref fCoalHueName, value); }
        }
        string fGoldHueName;
        [Size(16)]
        public string GoldHueName
        {
            get { return fGoldHueName; }
            set { SetPropertyValue<string>("GoldHueName", ref fGoldHueName, value); }
        }
        string fCustomHueName;
        [Size(16)]
        public string CustomHueName
        {
            get { return fCustomHueName; }
            set { SetPropertyValue<string>("CustomHueName", ref fCustomHueName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        [Association(@"LithologyReferencesDictionaryHue", typeof(Lithology))]
        public XPCollection<Lithology> Lithologys { get { return GetCollection<Lithology>("Lithologys"); } }
    }

}
