//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryPosition")]
    public partial class DictionaryPosition : XPLiteObject
    {
        Guid fPositionID;
        [Key(true)]
        public Guid PositionID
        {
            get { return fPositionID; }
            set { SetPropertyValue<Guid>("PositionID", ref fPositionID, value); }
        }
        string fStandardPositionName;
        [Size(16)]
        public string StandardPositionName
        {
            get { return fStandardPositionName; }
            set { SetPropertyValue<string>("StandardPositionName", ref fStandardPositionName, value); }
        }
        string fCoalPositionName;
        [Size(16)]
        public string CoalPositionName
        {
            get { return fCoalPositionName; }
            set { SetPropertyValue<string>("CoalPositionName", ref fCoalPositionName, value); }
        }
        string fGoldPositionName;
        [Size(16)]
        public string GoldPositionName
        {
            get { return fGoldPositionName; }
            set { SetPropertyValue<string>("GoldPositionName", ref fGoldPositionName, value); }
        }
        string fCustomPositionName;
        [Size(16)]
        public string CustomPositionName
        {
            get { return fCustomPositionName; }
            set { SetPropertyValue<string>("CustomPositionName", ref fCustomPositionName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fFullDescription;
        [Size(SizeAttribute.Unlimited)]
        public string FullDescription
        {
            get { return fFullDescription; }
            set { SetPropertyValue<string>("FullDescription", ref fFullDescription, value); }
        }
        byte[] fThumbnail;
        [Size(SizeAttribute.Unlimited)]
        public byte[] Thumbnail
        {
            get { return fThumbnail; }
            set { SetPropertyValue<byte[]>("Thumbnail", ref fThumbnail, value); }
        }
        FileData fOriginalFileDataID;
        [Association(@"X_DictionaryPositionReferencesFileData")]
        public FileData OriginalFileDataID
        {
            get { return fOriginalFileDataID; }
            set { SetPropertyValue<FileData>("OriginalFileDataID", ref fOriginalFileDataID, value); }
        }
        [Association(@"ExperienceReferencesX_DictionaryPosition", typeof(Experience))]
        public XPCollection<Experience> Experiences { get { return GetCollection<Experience>("Experiences"); } }
    }

}
