//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryCharacteristic")]
    public partial class DictionaryCharacteristic : XPLiteObject
    {
        Guid fCharacteristicID;
        [Key(true)]
        public Guid CharacteristicID
        {
            get { return fCharacteristicID; }
            set { SetPropertyValue<Guid>("CharacteristicID", ref fCharacteristicID, value); }
        }
        string fStandardCharacteristicName;
        [Size(60)]
        public string StandardCharacteristicName
        {
            get { return fStandardCharacteristicName; }
            set { SetPropertyValue<string>("StandardCharacteristicName", ref fStandardCharacteristicName, value); }
        }
        string fCustomCharacteristicName;
        [Size(60)]
        public string CustomCharacteristicName
        {
            get { return fCustomCharacteristicName; }
            set { SetPropertyValue<string>("CustomCharacteristicName", ref fCustomCharacteristicName, value); }
        }
        DictionaryUnit fUnitID;
        [Association(@"X_DictionaryCharacteristicReferencesDictionaryUnit")]
        public DictionaryUnit UnitID
        {
            get { return fUnitID; }
            set { SetPropertyValue<DictionaryUnit>("UnitID", ref fUnitID, value); }
        }
        DictionaryCharacteristicType fCharacteristicTypeID;
        [Association(@"X_DictionaryCharacteristicReferencesX_DictionaryCharacteristicType")]
        public DictionaryCharacteristicType CharacteristicTypeID
        {
            get { return fCharacteristicTypeID; }
            set { SetPropertyValue<DictionaryCharacteristicType>("CharacteristicTypeID", ref fCharacteristicTypeID, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fFullDescription;
        [Size(SizeAttribute.Unlimited)]
        public string FullDescription
        {
            get { return fFullDescription; }
            set { SetPropertyValue<string>("FullDescription", ref fFullDescription, value); }
        }
        byte[] fThumbnail;
        [Size(SizeAttribute.Unlimited)]
        public byte[] Thumbnail
        {
            get { return fThumbnail; }
            set { SetPropertyValue<byte[]>("Thumbnail", ref fThumbnail, value); }
        }
        FileData fOriginalFileDataID;
        [Association(@"X_DictionaryCharacteristicReferencesFileData")]
        public FileData OriginalFileDataID
        {
            get { return fOriginalFileDataID; }
            set { SetPropertyValue<FileData>("OriginalFileDataID", ref fOriginalFileDataID, value); }
        }
        [Association(@"X_ModelCharacteristicReferencesX_DictionaryCharacteristic", typeof(ModelCharacteristic))]
        public XPCollection<ModelCharacteristic> X_ModelCharacteristics { get { return GetCollection<ModelCharacteristic>("X_ModelCharacteristics"); } }
        [Association(@"X_PartCharacteristicReferencesX_DictionaryCharacteristic", typeof(PartCharacteristic))]
        public XPCollection<PartCharacteristic> X_PartCharacteristics { get { return GetCollection<PartCharacteristic>("X_PartCharacteristics"); } }
    }

}
