//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryRelationType")]
    public partial class DictionaryRelationType : XPLiteObject
    {
        Guid fRelationTypeID;
        [Key(true)]
        public Guid RelationTypeID
        {
            get { return fRelationTypeID; }
            set { SetPropertyValue<Guid>("RelationTypeID", ref fRelationTypeID, value); }
        }
        string fStandardRelationTypeName;
        [Indexed(Name = @"IDictionaryRelationType", Unique = true)]
        [Size(16)]
        public string StandardRelationTypeName
        {
            get { return fStandardRelationTypeName; }
            set { SetPropertyValue<string>("StandardRelationTypeName", ref fStandardRelationTypeName, value); }
        }
        string fCoalRelationTypeName;
        [Size(16)]
        public string CoalRelationTypeName
        {
            get { return fCoalRelationTypeName; }
            set { SetPropertyValue<string>("CoalRelationTypeName", ref fCoalRelationTypeName, value); }
        }
        string fGoldRelationTypeName;
        [Size(16)]
        public string GoldRelationTypeName
        {
            get { return fGoldRelationTypeName; }
            set { SetPropertyValue<string>("GoldRelationTypeName", ref fGoldRelationTypeName, value); }
        }
        string fCustomRelationTypeName;
        [Size(16)]
        public string CustomRelationTypeName
        {
            get { return fCustomRelationTypeName; }
            set { SetPropertyValue<string>("CustomRelationTypeName", ref fCustomRelationTypeName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fFullDescription;
        [Size(SizeAttribute.Unlimited)]
        public string FullDescription
        {
            get { return fFullDescription; }
            set { SetPropertyValue<string>("FullDescription", ref fFullDescription, value); }
        }
        byte[] fThumbnail;
        [Size(SizeAttribute.Unlimited)]
        public byte[] Thumbnail
        {
            get { return fThumbnail; }
            set { SetPropertyValue<byte[]>("Thumbnail", ref fThumbnail, value); }
        }
        FileData fOriginalFileDataID;
        [Association(@"DictionaryRelationTypeReferencesFileData")]
        public FileData OriginalFileDataID
        {
            get { return fOriginalFileDataID; }
            set { SetPropertyValue<FileData>("OriginalFileDataID", ref fOriginalFileDataID, value); }
        }
        [Association(@"HeaderRelationReferencesDictionaryRelationType", typeof(HeaderRelation))]
        public XPCollection<HeaderRelation> HeaderRelations { get { return GetCollection<HeaderRelation>("HeaderRelations"); } }
        [Association(@"X_DictionaryModelRelationReferencesDictionaryRelationType", typeof(DictionaryModelRelation))]
        public XPCollection<DictionaryModelRelation> X_DictionaryModelRelations { get { return GetCollection<DictionaryModelRelation>("X_DictionaryModelRelations"); } }
    }

}
