//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryLeaseApplicationType")]
    public partial class DictionaryLeaseApplicationType : XPLiteObject
    {
        Guid fLeaseApplicationTypeID;
        [Key(true)]
        public Guid LeaseApplicationTypeID
        {
            get { return fLeaseApplicationTypeID; }
            set { SetPropertyValue<Guid>("LeaseApplicationTypeID", ref fLeaseApplicationTypeID, value); }
        }
        string fStandardLeaseApplicationTypeName;
        [Indexed(Name = @"IDictionaryLeaseApplicationType", Unique = true)]
        [Size(16)]
        public string StandardLeaseApplicationTypeName
        {
            get { return fStandardLeaseApplicationTypeName; }
            set { SetPropertyValue<string>("StandardLeaseApplicationTypeName", ref fStandardLeaseApplicationTypeName, value); }
        }
        string fCoalLeaseApplicationTypeName;
        [Size(16)]
        public string CoalLeaseApplicationTypeName
        {
            get { return fCoalLeaseApplicationTypeName; }
            set { SetPropertyValue<string>("CoalLeaseApplicationTypeName", ref fCoalLeaseApplicationTypeName, value); }
        }
        string fGoldLeaseApplicationTypeName;
        [Size(16)]
        public string GoldLeaseApplicationTypeName
        {
            get { return fGoldLeaseApplicationTypeName; }
            set { SetPropertyValue<string>("GoldLeaseApplicationTypeName", ref fGoldLeaseApplicationTypeName, value); }
        }
        string fCustomLeaseApplicationTypeName;
        [Size(16)]
        public string CustomLeaseApplicationTypeName
        {
            get { return fCustomLeaseApplicationTypeName; }
            set { SetPropertyValue<string>("CustomLeaseApplicationTypeName", ref fCustomLeaseApplicationTypeName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        [Association(@"LeaseApplicationReferencesDictionaryLeaseApplicationType", typeof(LeaseApplication))]
        public XPCollection<LeaseApplication> LeaseApplications { get { return GetCollection<LeaseApplication>("LeaseApplications"); } }
    }

}
