//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryPointLoadTestType")]
    public partial class DictionaryPointLoadTestType : XPLiteObject
    {
        Guid fPointLoadTestTypeID;
        [Key(true)]
        public Guid PointLoadTestTypeID
        {
            get { return fPointLoadTestTypeID; }
            set { SetPropertyValue<Guid>("PointLoadTestTypeID", ref fPointLoadTestTypeID, value); }
        }
        string fStandardPointLoadTestTypeName;
        [Indexed(Name = @"IDictionaryPointLoadTestType", Unique = true)]
        [Size(16)]
        public string StandardPointLoadTestTypeName
        {
            get { return fStandardPointLoadTestTypeName; }
            set { SetPropertyValue<string>("StandardPointLoadTestTypeName", ref fStandardPointLoadTestTypeName, value); }
        }
        string fCoalPointLoadTestTypeName;
        [Size(16)]
        public string CoalPointLoadTestTypeName
        {
            get { return fCoalPointLoadTestTypeName; }
            set { SetPropertyValue<string>("CoalPointLoadTestTypeName", ref fCoalPointLoadTestTypeName, value); }
        }
        string fGoldPointLoadTestTypeName;
        [Size(16)]
        public string GoldPointLoadTestTypeName
        {
            get { return fGoldPointLoadTestTypeName; }
            set { SetPropertyValue<string>("GoldPointLoadTestTypeName", ref fGoldPointLoadTestTypeName, value); }
        }
        string fCustomPointLoadTestTypeName;
        [Size(16)]
        public string CustomPointLoadTestTypeName
        {
            get { return fCustomPointLoadTestTypeName; }
            set { SetPropertyValue<string>("CustomPointLoadTestTypeName", ref fCustomPointLoadTestTypeName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        [Association(@"PointLoadReferencesDictionaryPointLoadTestType", typeof(PointLoad))]
        public XPCollection<PointLoad> PointLoads { get { return GetCollection<PointLoad>("PointLoads"); } }
    }

}
