//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionarySeamAlias")]
    public partial class DictionarySeamAlias : XPLiteObject
    {
        Guid fSeamAliasID;
        [Key(true)]
        public Guid SeamAliasID
        {
            get { return fSeamAliasID; }
            set { SetPropertyValue<Guid>("SeamAliasID", ref fSeamAliasID, value); }
        }
        DictionarySeam fSeamID;
        [Association(@"DictionarySeamAliasReferencesDictionarySeam")]
        public DictionarySeam SeamID
        {
            get { return fSeamID; }
            set { SetPropertyValue<DictionarySeam>("SeamID", ref fSeamID, value); }
        }
        string fCustomSeamName;
        [Size(16)]
        public string CustomSeamName
        {
            get { return fCustomSeamName; }
            set { SetPropertyValue<string>("CustomSeamName", ref fCustomSeamName, value); }
        }
        string fFullDescription;
        [Size(SizeAttribute.Unlimited)]
        public string FullDescription
        {
            get { return fFullDescription; }
            set { SetPropertyValue<string>("FullDescription", ref fFullDescription, value); }
        }
        byte[] fThumbnail;
        [Size(SizeAttribute.Unlimited)]
        public byte[] Thumbnail
        {
            get { return fThumbnail; }
            set { SetPropertyValue<byte[]>("Thumbnail", ref fThumbnail, value); }
        }
        FileData fOriginalFileDataID;
        [Association(@"DictionarySeamAliasReferencesFileData")]
        public FileData OriginalFileDataID
        {
            get { return fOriginalFileDataID; }
            set { SetPropertyValue<FileData>("OriginalFileDataID", ref fOriginalFileDataID, value); }
        }
    }

}
