//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryDrillFluid")]
    public partial class DictionaryDrillFluid : XPLiteObject
    {
        Guid fDrillFluidID;
        [Key(true)]
        public Guid DrillFluidID
        {
            get { return fDrillFluidID; }
            set { SetPropertyValue<Guid>("DrillFluidID", ref fDrillFluidID, value); }
        }
        string fStandardDrillFluidName;
        [Indexed(Name = @"IDictionaryDrillFluid", Unique = true)]
        [Size(16)]
        public string StandardDrillFluidName
        {
            get { return fStandardDrillFluidName; }
            set { SetPropertyValue<string>("StandardDrillFluidName", ref fStandardDrillFluidName, value); }
        }
        string fCoalDrillFluidName;
        [Size(16)]
        public string CoalDrillFluidName
        {
            get { return fCoalDrillFluidName; }
            set { SetPropertyValue<string>("CoalDrillFluidName", ref fCoalDrillFluidName, value); }
        }
        string fGoldDrillFluidName;
        [Size(16)]
        public string GoldDrillFluidName
        {
            get { return fGoldDrillFluidName; }
            set { SetPropertyValue<string>("GoldDrillFluidName", ref fGoldDrillFluidName, value); }
        }
        string fCustomDrillFluidName;
        [Size(16)]
        public string CustomDrillFluidName
        {
            get { return fCustomDrillFluidName; }
            set { SetPropertyValue<string>("CustomDrillFluidName", ref fCustomDrillFluidName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fFullDescription;
        [Size(SizeAttribute.Unlimited)]
        public string FullDescription
        {
            get { return fFullDescription; }
            set { SetPropertyValue<string>("FullDescription", ref fFullDescription, value); }
        }
        System.Drawing.Image fThumbnail;
        [Size(SizeAttribute.Unlimited)]
        [ValueConverter(typeof(DevExpress.Xpo.Metadata.ImageValueConverter))]
        public System.Drawing.Image Thumbnail
        {
            get { return fThumbnail; }
            set { SetPropertyValue<System.Drawing.Image>("Thumbnail", ref fThumbnail, value); }
        }
        FileData fOriginalFileDataID;
        [Association(@"DictionaryDrillFluidReferencesFileData")]
        public FileData OriginalFileDataID
        {
            get { return fOriginalFileDataID; }
            set { SetPropertyValue<FileData>("OriginalFileDataID", ref fOriginalFileDataID, value); }
        }
        [Association(@"DrillingReferencesDictionaryDrillFluid", typeof(Drilling))]
        public XPCollection<Drilling> Drillings { get { return GetCollection<Drilling>("Drillings"); } }
    }

}
