//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"Q_DictionaryPartCategory")]
    public partial class DictionaryPartCategory : XPLiteObject
    {
        Guid fPartCategoryID;
        [Key(true)]
        public Guid PartCategoryID
        {
            get { return fPartCategoryID; }
            set { SetPropertyValue<Guid>("PartCategoryID", ref fPartCategoryID, value); }
        }
        DictionaryPart fPartID;
        [Association(@"DictionaryPartCategoryReferencesQ_DictionaryPart")]
        public DictionaryPart PartID
        {
            get { return fPartID; }
            set { SetPropertyValue<DictionaryPart>("PartID", ref fPartID, value); }
        }
        DictionaryDeviceType fCategoryDeviceTypeID;
        [Association(@"DictionaryPartCategoryReferencesDictionaryDeviceType")]
        public DictionaryDeviceType CategoryDeviceTypeID
        {
            get { return fCategoryDeviceTypeID; }
            set { SetPropertyValue<DictionaryDeviceType>("CategoryDeviceTypeID", ref fCategoryDeviceTypeID, value); }
        }
    }

}
