//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryPlyAlias")]
    public partial class DictionaryPlyAlias : XPLiteObject
    {
        Guid fPlyAliasID;
        [Key(true)]
        public Guid PlyAliasID
        {
            get { return fPlyAliasID; }
            set { SetPropertyValue<Guid>("PlyAliasID", ref fPlyAliasID, value); }
        }
        DictionaryPly fPlyID;
        [Association(@"DictionaryPlyAliasReferencesDictionaryPly")]
        public DictionaryPly PlyID
        {
            get { return fPlyID; }
            set { SetPropertyValue<DictionaryPly>("PlyID", ref fPlyID, value); }
        }
        string fCustomPlyName;
        [Size(16)]
        public string CustomPlyName
        {
            get { return fCustomPlyName; }
            set { SetPropertyValue<string>("CustomPlyName", ref fCustomPlyName, value); }
        }
        string fFullDescription;
        [Size(SizeAttribute.Unlimited)]
        public string FullDescription
        {
            get { return fFullDescription; }
            set { SetPropertyValue<string>("FullDescription", ref fFullDescription, value); }
        }
        System.Drawing.Image fThumbnail;
        [Size(SizeAttribute.Unlimited)]
        [ValueConverter(typeof(DevExpress.Xpo.Metadata.ImageValueConverter))]
        public System.Drawing.Image Thumbnail
        {
            get { return fThumbnail; }
            set { SetPropertyValue<System.Drawing.Image>("Thumbnail", ref fThumbnail, value); }
        }
        FileData fOriginalFileDataID;
        [Association(@"DictionaryPlyAliasReferencesFileData")]
        public FileData OriginalFileDataID
        {
            get { return fOriginalFileDataID; }
            set { SetPropertyValue<FileData>("OriginalFileDataID", ref fOriginalFileDataID, value); }
        }
    }

}
