//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DictionaryAssayType")]
    public partial class DictionaryAssayType : XPLiteObject
    {
        Guid fAssayTypeID;
        [Key(true)]
        public Guid AssayTypeID
        {
            get { return fAssayTypeID; }
            set { SetPropertyValue<Guid>("AssayTypeID", ref fAssayTypeID, value); }
        }
        string fStandardAssayTypeName;
        [Indexed(Name = @"IDictionaryAssayType", Unique = true)]
        [Size(16)]
        public string StandardAssayTypeName
        {
            get { return fStandardAssayTypeName; }
            set { SetPropertyValue<string>("StandardAssayTypeName", ref fStandardAssayTypeName, value); }
        }
        string fCoalAssayTypeName;
        [Size(16)]
        public string CoalAssayTypeName
        {
            get { return fCoalAssayTypeName; }
            set { SetPropertyValue<string>("CoalAssayTypeName", ref fCoalAssayTypeName, value); }
        }
        string fGoldAssayTypeName;
        [Size(16)]
        public string GoldAssayTypeName
        {
            get { return fGoldAssayTypeName; }
            set { SetPropertyValue<string>("GoldAssayTypeName", ref fGoldAssayTypeName, value); }
        }
        string fCustomAssayTypeName;
        [Size(16)]
        public string CustomAssayTypeName
        {
            get { return fCustomAssayTypeName; }
            set { SetPropertyValue<string>("CustomAssayTypeName", ref fCustomAssayTypeName, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fFullDescription;
        [Size(SizeAttribute.Unlimited)]
        public string FullDescription
        {
            get { return fFullDescription; }
            set { SetPropertyValue<string>("FullDescription", ref fFullDescription, value); }
        }
        System.Drawing.Image fThumbnail;
        [Size(SizeAttribute.Unlimited)]
        [ValueConverter(typeof(DevExpress.Xpo.Metadata.ImageValueConverter))]
        public System.Drawing.Image Thumbnail
        {
            get { return fThumbnail; }
            set { SetPropertyValue<System.Drawing.Image>("Thumbnail", ref fThumbnail, value); }
        }
        FileData fOriginalFileDataID;
        [Association(@"DictionaryAssayTypeReferencesFileData")]
        public FileData OriginalFileDataID
        {
            get { return fOriginalFileDataID; }
            set { SetPropertyValue<FileData>("OriginalFileDataID", ref fOriginalFileDataID, value); }
        }
        [Association(@"AssayGroupTestReferencesDictionaryAssayType", typeof(AssayGroupTest))]
        public XPCollection<AssayGroupTest> AssayGroupTests { get { return GetCollection<AssayGroupTest>("AssayGroupTests"); } }
    }

}
