//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DrillingCompany")]
    public partial class DrillingCompany : XPLiteObject
    {
        Guid fDrillingCompanyID;
        [Key(true)]
        public Guid DrillingCompanyID
        {
            get { return fDrillingCompanyID; }
            set { SetPropertyValue<Guid>("DrillingCompanyID", ref fDrillingCompanyID, value); }
        }
        Company fCompanyID;
        [Association(@"DrillingCompanyReferencesCompany")]
        public Company CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<Company>("CompanyID", ref fCompanyID, value); }
        }
        [Association(@"DrillCompanyContractReferencesDrillingCompany", typeof(DrillCompanyContract))]
        public XPCollection<DrillCompanyContract> DrillCompanyContracts { get { return GetCollection<DrillCompanyContract>("DrillCompanyContracts"); } }
        [Association(@"DrillingReferencesDrillingCompany", typeof(Drilling))]
        public XPCollection<Drilling> Drillings { get { return GetCollection<Drilling>("Drillings"); } }
    }

}
