//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_DrillCompanyContract")]
    public partial class DrillCompanyContract : XPLiteObject
    {
        Guid fDrillContractID;
        [Key(true)]
        public Guid DrillContractID
        {
            get { return fDrillContractID; }
            set { SetPropertyValue<Guid>("DrillContractID", ref fDrillContractID, value); }
        }
        Guid fDrillingCompanyID;
        public Guid DrillingCompanyID
        {
            get { return fDrillingCompanyID; }
            set { SetPropertyValue<Guid>("DrillingCompanyID", ref fDrillingCompanyID, value); }
        }
        string fContractName;
        [Size(16)]
        public string ContractName
        {
            get { return fContractName; }
            set { SetPropertyValue<string>("ContractName", ref fContractName, value); }
        }
        Project fProjectID;
        [Association(@"DrillCompanyContractReferencesProject")]
        public Project ProjectID
        {
            get { return fProjectID; }
            set { SetPropertyValue<Project>("ProjectID", ref fProjectID, value); }
        }
        string fTask;
        [Size(255)]
        public string Task
        {
            get { return fTask; }
            set { SetPropertyValue<string>("Task", ref fTask, value); }
        }
        DateTime fStarted;
        public DateTime Started
        {
            get { return fStarted; }
            set { SetPropertyValue<DateTime>("Started", ref fStarted, value); }
        }
        DateTime fEnded;
        public DateTime Ended
        {
            get { return fEnded; }
            set { SetPropertyValue<DateTime>("Ended", ref fEnded, value); }
        }
        DateTime fCompleted;
        public DateTime Completed
        {
            get { return fCompleted; }
            set { SetPropertyValue<DateTime>("Completed", ref fCompleted, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>("Comment", ref fComment, value); }
        }
    }

}
