//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"E_Invoice")]
    public partial class Invoice : XPLiteObject
    {
        Guid fInvoiceID;
        [Key(true)]
        public Guid InvoiceID
        {
            get { return fInvoiceID; }
            set { SetPropertyValue<Guid>("InvoiceID", ref fInvoiceID, value); }
        }
        int fSequence;
        public int Sequence
        {
            get { return fSequence; }
            set { SetPropertyValue<int>("Sequence", ref fSequence, value); }
        }
        Company fSupplierCompanyID;
        [Association(@"InvoiceReferencesCompany")]
        public Company SupplierCompanyID
        {
            get { return fSupplierCompanyID; }
            set { SetPropertyValue<Company>("SupplierCompanyID", ref fSupplierCompanyID, value); }
        }
        CompanyAddress fSupplierCompanyAddressID;
        [Association(@"InvoiceReferencesCompanyAddress")]
        public CompanyAddress SupplierCompanyAddressID
        {
            get { return fSupplierCompanyAddressID; }
            set { SetPropertyValue<CompanyAddress>("SupplierCompanyAddressID", ref fSupplierCompanyAddressID, value); }
        }
        Account fSupplierAccountID;
        [Association(@"InvoiceReferencesQ_Account")]
        public Account SupplierAccountID
        {
            get { return fSupplierAccountID; }
            set { SetPropertyValue<Account>("SupplierAccountID", ref fSupplierAccountID, value); }
        }
        string fSupplierReferenceNumber;
        [Size(60)]
        public string SupplierReferenceNumber
        {
            get { return fSupplierReferenceNumber; }
            set { SetPropertyValue<string>("SupplierReferenceNumber", ref fSupplierReferenceNumber, value); }
        }
        Company fCustomerCompanyID;
        [Association(@"InvoiceReferencesCompany1")]
        public Company CustomerCompanyID
        {
            get { return fCustomerCompanyID; }
            set { SetPropertyValue<Company>("CustomerCompanyID", ref fCustomerCompanyID, value); }
        }
        CompanyAddress fCustomerCompanyAddressID;
        [Association(@"InvoiceReferencesCompanyAddress1")]
        public CompanyAddress CustomerCompanyAddressID
        {
            get { return fCustomerCompanyAddressID; }
            set { SetPropertyValue<CompanyAddress>("CustomerCompanyAddressID", ref fCustomerCompanyAddressID, value); }
        }
        Account fCustomerAccountID;
        [Association(@"InvoiceReferencesQ_Account1")]
        public Account CustomerAccountID
        {
            get { return fCustomerAccountID; }
            set { SetPropertyValue<Account>("CustomerAccountID", ref fCustomerAccountID, value); }
        }
        string fCustomerReferenceNumber;
        [Size(60)]
        public string CustomerReferenceNumber
        {
            get { return fCustomerReferenceNumber; }
            set { SetPropertyValue<string>("CustomerReferenceNumber", ref fCustomerReferenceNumber, value); }
        }
        decimal fFreightTax;
        public decimal FreightTax
        {
            get { return fFreightTax; }
            set { SetPropertyValue<decimal>("FreightTax", ref fFreightTax, value); }
        }
        decimal fFreightAmount;
        public decimal FreightAmount
        {
            get { return fFreightAmount; }
            set { SetPropertyValue<decimal>("FreightAmount", ref fFreightAmount, value); }
        }
        bool fDiscountIncludesFreight;
        public bool DiscountIncludesFreight
        {
            get { return fDiscountIncludesFreight; }
            set { SetPropertyValue<bool>("DiscountIncludesFreight", ref fDiscountIncludesFreight, value); }
        }
        bool fDiscountAllFreight;
        public bool DiscountAllFreight
        {
            get { return fDiscountAllFreight; }
            set { SetPropertyValue<bool>("DiscountAllFreight", ref fDiscountAllFreight, value); }
        }
        decimal fDiscountAmount;
        public decimal DiscountAmount
        {
            get { return fDiscountAmount; }
            set { SetPropertyValue<decimal>("DiscountAmount", ref fDiscountAmount, value); }
        }
        decimal fTaxAmount;
        public decimal TaxAmount
        {
            get { return fTaxAmount; }
            set { SetPropertyValue<decimal>("TaxAmount", ref fTaxAmount, value); }
        }
        decimal fTotal;
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>("Total", ref fTotal, value); }
        }
        DateTime fDated;
        public DateTime Dated
        {
            get { return fDated; }
            set { SetPropertyValue<DateTime>("Dated", ref fDated, value); }
        }
        DateTime fCommunicated;
        public DateTime Communicated
        {
            get { return fCommunicated; }
            set { SetPropertyValue<DateTime>("Communicated", ref fCommunicated, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>("Version", ref fVersion, value); }
        }
        Guid fVersionAntecedentID;
        public Guid VersionAntecedentID
        {
            get { return fVersionAntecedentID; }
            set { SetPropertyValue<Guid>("VersionAntecedentID", ref fVersionAntecedentID, value); }
        }
        int fVersionCertainty;
        public int VersionCertainty
        {
            get { return fVersionCertainty; }
            set { SetPropertyValue<int>("VersionCertainty", ref fVersionCertainty, value); }
        }
        Guid fVersionWorkflowInstanceID;
        public Guid VersionWorkflowInstanceID
        {
            get { return fVersionWorkflowInstanceID; }
            set { SetPropertyValue<Guid>("VersionWorkflowInstanceID", ref fVersionWorkflowInstanceID, value); }
        }
        Guid fVersionUpdatedBy;
        public Guid VersionUpdatedBy
        {
            get { return fVersionUpdatedBy; }
            set { SetPropertyValue<Guid>("VersionUpdatedBy", ref fVersionUpdatedBy, value); }
        }
        Guid fVersionDeletedBy;
        public Guid VersionDeletedBy
        {
            get { return fVersionDeletedBy; }
            set { SetPropertyValue<Guid>("VersionDeletedBy", ref fVersionDeletedBy, value); }
        }
        Guid fVersionOwnerContactID;
        public Guid VersionOwnerContactID
        {
            get { return fVersionOwnerContactID; }
            set { SetPropertyValue<Guid>("VersionOwnerContactID", ref fVersionOwnerContactID, value); }
        }
        Guid fVersionOwnerCompanyID;
        public Guid VersionOwnerCompanyID
        {
            get { return fVersionOwnerCompanyID; }
            set { SetPropertyValue<Guid>("VersionOwnerCompanyID", ref fVersionOwnerCompanyID, value); }
        }
        DateTime fVersionUpdated;
        public DateTime VersionUpdated
        {
            get { return fVersionUpdated; }
            set { SetPropertyValue<DateTime>("VersionUpdated", ref fVersionUpdated, value); }
        }
        decimal fOriginalTotal;
        public decimal OriginalTotal
        {
            get { return fOriginalTotal; }
            set { SetPropertyValue<decimal>("OriginalTotal", ref fOriginalTotal, value); }
        }
        Currency fCurrencyID;
        [Association(@"InvoiceReferencesE_Currency")]
        public Currency CurrencyID
        {
            get { return fCurrencyID; }
            set { SetPropertyValue<Currency>("CurrencyID", ref fCurrencyID, value); }
        }
        [Association(@"SupplyReferencesE_Invoice", typeof(Supply))]
        public XPCollection<Supply> Supplies { get { return GetCollection<Supply>("Supplies"); } }
        [Association(@"SupplyReferencesE_Invoice1", typeof(Supply))]
        public XPCollection<Supply> Supplies1 { get { return GetCollection<Supply>("Supplies1"); } }
        [Association(@"InvoiceLineReferencesE_Invoice", typeof(InvoiceLine))]
        public XPCollection<InvoiceLine> InvoiceLines { get { return GetCollection<InvoiceLine>("InvoiceLines"); } }
        [Association(@"CreditReferencesInvoice", typeof(Credit))]
        public XPCollection<Credit> Credits { get { return GetCollection<Credit>("Credits"); } }
    }

}
