//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_MetaData")]
    public partial class MetaData : XPLiteObject
    {
        Guid fMetaDataID;
        [Key(true)]
        public Guid MetaDataID
        {
            get { return fMetaDataID; }
            set { SetPropertyValue<Guid>("MetaDataID", ref fMetaDataID, value); }
        }
        string fMetaDataType;
        [Size(50)]
        public string MetaDataType
        {
            get { return fMetaDataType; }
            set { SetPropertyValue<string>("MetaDataType", ref fMetaDataType, value); }
        }
        string fContentToIndex;
        [Size(SizeAttribute.Unlimited)]
        public string ContentToIndex
        {
            get { return fContentToIndex; }
            set { SetPropertyValue<string>("ContentToIndex", ref fContentToIndex, value); }
        }
        [Association(@"MetaDataRelationReferencesMetaData", typeof(MetaDataRelation))]
        public XPCollection<MetaDataRelation> MetaDataRelations { get { return GetCollection<MetaDataRelation>("MetaDataRelations"); } }
    }

}
