//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_ProjectPlanTaskResponse")]
    public partial class ProjectPlanTaskResponse : XPLiteObject
    {
        Guid fProjectPlanTaskResponseID;
        [Key(true)]
        public Guid ProjectPlanTaskResponseID
        {
            get { return fProjectPlanTaskResponseID; }
            set { SetPropertyValue<Guid>("ProjectPlanTaskResponseID", ref fProjectPlanTaskResponseID, value); }
        }
        ProjectPlanTask fProjectPlanTaskID;
        [Association(@"ProjectPlanTaskResponseReferencesProjectPlanTask")]
        public ProjectPlanTask ProjectPlanTaskID
        {
            get { return fProjectPlanTaskID; }
            set { SetPropertyValue<ProjectPlanTask>("ProjectPlanTaskID", ref fProjectPlanTaskID, value); }
        }
        Contact fResponsibleContactID;
        [Association(@"ProjectPlanTaskResponseReferencesContact")]
        public Contact ResponsibleContactID
        {
            get { return fResponsibleContactID; }
            set { SetPropertyValue<Contact>("ResponsibleContactID", ref fResponsibleContactID, value); }
        }
        DateTime fCompleted;
        public DateTime Completed
        {
            get { return fCompleted; }
            set { SetPropertyValue<DateTime>("Completed", ref fCompleted, value); }
        }
        string fComments;
        [Size(255)]
        public string Comments
        {
            get { return fComments; }
            set { SetPropertyValue<string>("Comments", ref fComments, value); }
        }
    }

}
