//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_ProjectPlanTaskWorker")]
    public partial class ProjectPlanTaskWorker : XPLiteObject
    {
        Guid fProjectPlanTaskWorkerID;
        [Key(true)]
        public Guid ProjectPlanTaskWorkerID
        {
            get { return fProjectPlanTaskWorkerID; }
            set { SetPropertyValue<Guid>("ProjectPlanTaskWorkerID", ref fProjectPlanTaskWorkerID, value); }
        }
        ProjectPlanTask fProjectPlanTaskID;
        [Association(@"ProjectPlanTaskWorkerReferencesProjectPlanTask")]
        public ProjectPlanTask ProjectPlanTaskID
        {
            get { return fProjectPlanTaskID; }
            set { SetPropertyValue<ProjectPlanTask>("ProjectPlanTaskID", ref fProjectPlanTaskID, value); }
        }
        Worker fWorkerID;
        [Association(@"ProjectPlanTaskWorkerReferencesWorker")]
        public Worker WorkerID
        {
            get { return fWorkerID; }
            set { SetPropertyValue<Worker>("WorkerID", ref fWorkerID, value); }
        }
        DateTime fAvailableFromDate;
        public DateTime AvailableFromDate
        {
            get { return fAvailableFromDate; }
            set { SetPropertyValue<DateTime>("AvailableFromDate", ref fAvailableFromDate, value); }
        }
        DateTime fAvailableUntilDate;
        public DateTime AvailableUntilDate
        {
            get { return fAvailableUntilDate; }
            set { SetPropertyValue<DateTime>("AvailableUntilDate", ref fAvailableUntilDate, value); }
        }
    }

}
