//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"Q_ProjectPlanTaskPart")]
    public partial class ProjectPlanTaskPart : XPLiteObject
    {
        Guid fProjectPlanTaskPartID;
        [Key(true)]
        public Guid ProjectPlanTaskPartID
        {
            get { return fProjectPlanTaskPartID; }
            set { SetPropertyValue<Guid>("ProjectPlanTaskPartID", ref fProjectPlanTaskPartID, value); }
        }
        ProjectPlanTask fProjectPlanTaskID;
        [Association(@"ProjectPlanTaskPartReferencesProjectPlanTask")]
        public ProjectPlanTask ProjectPlanTaskID
        {
            get { return fProjectPlanTaskID; }
            set { SetPropertyValue<ProjectPlanTask>("ProjectPlanTaskID", ref fProjectPlanTaskID, value); }
        }
        DictionaryPart fPartID;
        [Association(@"ProjectPlanTaskPartReferencesQ_DictionaryPart")]
        public DictionaryPart PartID
        {
            get { return fPartID; }
            set { SetPropertyValue<DictionaryPart>("PartID", ref fPartID, value); }
        }
        DictionaryUnit fQuantityUnitID;
        [Association(@"ProjectPlanTaskPartReferencesDictionaryUnit")]
        public DictionaryUnit QuantityUnitID
        {
            get { return fQuantityUnitID; }
            set { SetPropertyValue<DictionaryUnit>("QuantityUnitID", ref fQuantityUnitID, value); }
        }
        decimal fQuantityOrdered;
        public decimal QuantityOrdered
        {
            get { return fQuantityOrdered; }
            set { SetPropertyValue<decimal>("QuantityOrdered", ref fQuantityOrdered, value); }
        }
        decimal fQuantityDespatched;
        public decimal QuantityDespatched
        {
            get { return fQuantityDespatched; }
            set { SetPropertyValue<decimal>("QuantityDespatched", ref fQuantityDespatched, value); }
        }
        decimal fQuantityReceived;
        public decimal QuantityReceived
        {
            get { return fQuantityReceived; }
            set { SetPropertyValue<decimal>("QuantityReceived", ref fQuantityReceived, value); }
        }
        decimal fQuantityUsed;
        public decimal QuantityUsed
        {
            get { return fQuantityUsed; }
            set { SetPropertyValue<decimal>("QuantityUsed", ref fQuantityUsed, value); }
        }
        DateTime fUsed;
        public DateTime Used
        {
            get { return fUsed; }
            set { SetPropertyValue<DateTime>("Used", ref fUsed, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>("Version", ref fVersion, value); }
        }
        Guid fVersionAntecedentID;
        public Guid VersionAntecedentID
        {
            get { return fVersionAntecedentID; }
            set { SetPropertyValue<Guid>("VersionAntecedentID", ref fVersionAntecedentID, value); }
        }
        int fVersionCertainty;
        public int VersionCertainty
        {
            get { return fVersionCertainty; }
            set { SetPropertyValue<int>("VersionCertainty", ref fVersionCertainty, value); }
        }
        Guid fVersionWorkflowInstanceID;
        public Guid VersionWorkflowInstanceID
        {
            get { return fVersionWorkflowInstanceID; }
            set { SetPropertyValue<Guid>("VersionWorkflowInstanceID", ref fVersionWorkflowInstanceID, value); }
        }
        Guid fVersionUpdatedBy;
        public Guid VersionUpdatedBy
        {
            get { return fVersionUpdatedBy; }
            set { SetPropertyValue<Guid>("VersionUpdatedBy", ref fVersionUpdatedBy, value); }
        }
        Guid fVersionDeletedBy;
        public Guid VersionDeletedBy
        {
            get { return fVersionDeletedBy; }
            set { SetPropertyValue<Guid>("VersionDeletedBy", ref fVersionDeletedBy, value); }
        }
        Guid fVersionOwnerContactID;
        public Guid VersionOwnerContactID
        {
            get { return fVersionOwnerContactID; }
            set { SetPropertyValue<Guid>("VersionOwnerContactID", ref fVersionOwnerContactID, value); }
        }
        Guid fVersionOwnerCompanyID;
        public Guid VersionOwnerCompanyID
        {
            get { return fVersionOwnerCompanyID; }
            set { SetPropertyValue<Guid>("VersionOwnerCompanyID", ref fVersionOwnerCompanyID, value); }
        }
        DateTime fVersionUpdated;
        public DateTime VersionUpdated
        {
            get { return fVersionUpdated; }
            set { SetPropertyValue<DateTime>("VersionUpdated", ref fVersionUpdated, value); }
        }
        WarehousePart fWarehousePartID;
        [Association(@"ProjectPlanTaskPartReferencesQ_WarehousePart")]
        public WarehousePart WarehousePartID
        {
            get { return fWarehousePartID; }
            set { SetPropertyValue<WarehousePart>("WarehousePartID", ref fWarehousePartID, value); }
        }
        SupplierPart fSupplierPartID;
        [Association(@"ProjectPlanTaskPartReferencesSupplierPart")]
        public SupplierPart SupplierPartID
        {
            get { return fSupplierPartID; }
            set { SetPropertyValue<SupplierPart>("SupplierPartID", ref fSupplierPartID, value); }
        }
        string fNote;
        [Size(255)]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>("Note", ref fNote, value); }
        }
        [Association(@"SupplyItemReferencesProjectPlanTaskPart", typeof(SupplyItem))]
        public XPCollection<SupplyItem> SupplyItems { get { return GetCollection<SupplyItem>("SupplyItems"); } }
    }

}
