//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_SecurityWhitelist")]
    public partial class SecurityWhitelist : XPLiteObject
    {
        Guid fSecurityWhitelistID;
        [Key(true)]
        public Guid SecurityWhitelistID
        {
            get { return fSecurityWhitelistID; }
            set { SetPropertyValue<Guid>("SecurityWhitelistID", ref fSecurityWhitelistID, value); }
        }
        Guid fOwnerApplicationID;
        [Indexed(Name = @"iOwnerApplicationID_SecurityWhitelist")]
        public Guid OwnerApplicationID
        {
            get { return fOwnerApplicationID; }
            set { SetPropertyValue<Guid>("OwnerApplicationID", ref fOwnerApplicationID, value); }
        }
        Company fOwnerCompanyID;
        [Association(@"SecurityWhitelistReferencesCompany")]
        public Company OwnerCompanyID
        {
            get { return fOwnerCompanyID; }
            set { SetPropertyValue<Company>("OwnerCompanyID", ref fOwnerCompanyID, value); }
        }
        Project fOwnerProjectID;
        [Association(@"SecurityWhitelistReferencesProject")]
        public Project OwnerProjectID
        {
            get { return fOwnerProjectID; }
            set { SetPropertyValue<Project>("OwnerProjectID", ref fOwnerProjectID, value); }
        }
        string fOwnerEntitySystemType;
        [Size(255)]
        public string OwnerEntitySystemType
        {
            get { return fOwnerEntitySystemType; }
            set { SetPropertyValue<string>("OwnerEntitySystemType", ref fOwnerEntitySystemType, value); }
        }
        Guid fAccessorApplicationID;
        [Indexed(Name = @"iAccessorApplicationID_SecurityWhitelist")]
        public Guid AccessorApplicationID
        {
            get { return fAccessorApplicationID; }
            set { SetPropertyValue<Guid>("AccessorApplicationID", ref fAccessorApplicationID, value); }
        }
        Company fAccessorCompanyID;
        [Association(@"SecurityWhitelistReferencesCompany1")]
        public Company AccessorCompanyID
        {
            get { return fAccessorCompanyID; }
            set { SetPropertyValue<Company>("AccessorCompanyID", ref fAccessorCompanyID, value); }
        }
        Project fAccessorProjectID;
        [Association(@"SecurityWhitelistReferencesProject1")]
        public Project AccessorProjectID
        {
            get { return fAccessorProjectID; }
            set { SetPropertyValue<Project>("AccessorProjectID", ref fAccessorProjectID, value); }
        }
        Contact fAccessorContactID;
        [Association(@"SecurityWhitelistReferencesContact")]
        public Contact AccessorContactID
        {
            get { return fAccessorContactID; }
            set { SetPropertyValue<Contact>("AccessorContactID", ref fAccessorContactID, value); }
        }
        Guid fAccessorRoleID;
        [Indexed(Name = @"iAccessorRoleID_SecurityWhitelist")]
        public Guid AccessorRoleID
        {
            get { return fAccessorRoleID; }
            set { SetPropertyValue<Guid>("AccessorRoleID", ref fAccessorRoleID, value); }
        }
        bool fCanCreate;
        public bool CanCreate
        {
            get { return fCanCreate; }
            set { SetPropertyValue<bool>("CanCreate", ref fCanCreate, value); }
        }
        bool fCanRead;
        public bool CanRead
        {
            get { return fCanRead; }
            set { SetPropertyValue<bool>("CanRead", ref fCanRead, value); }
        }
        bool fCanUpdate;
        public bool CanUpdate
        {
            get { return fCanUpdate; }
            set { SetPropertyValue<bool>("CanUpdate", ref fCanUpdate, value); }
        }
        bool fCanDelete;
        public bool CanDelete
        {
            get { return fCanDelete; }
            set { SetPropertyValue<bool>("CanDelete", ref fCanDelete, value); }
        }
        bool fIsField;
        public bool IsField
        {
            get { return fIsField; }
            set { SetPropertyValue<bool>("IsField", ref fIsField, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>("Version", ref fVersion, value); }
        }
        Guid fVersionAntecedentID;
        public Guid VersionAntecedentID
        {
            get { return fVersionAntecedentID; }
            set { SetPropertyValue<Guid>("VersionAntecedentID", ref fVersionAntecedentID, value); }
        }
        int fVersionCertainty;
        public int VersionCertainty
        {
            get { return fVersionCertainty; }
            set { SetPropertyValue<int>("VersionCertainty", ref fVersionCertainty, value); }
        }
        Guid fVersionWorkflowInstanceID;
        public Guid VersionWorkflowInstanceID
        {
            get { return fVersionWorkflowInstanceID; }
            set { SetPropertyValue<Guid>("VersionWorkflowInstanceID", ref fVersionWorkflowInstanceID, value); }
        }
        Guid fVersionUpdatedBy;
        public Guid VersionUpdatedBy
        {
            get { return fVersionUpdatedBy; }
            set { SetPropertyValue<Guid>("VersionUpdatedBy", ref fVersionUpdatedBy, value); }
        }
        Guid fVersionDeletedBy;
        public Guid VersionDeletedBy
        {
            get { return fVersionDeletedBy; }
            set { SetPropertyValue<Guid>("VersionDeletedBy", ref fVersionDeletedBy, value); }
        }
        Guid fVersionOwnerContactID;
        public Guid VersionOwnerContactID
        {
            get { return fVersionOwnerContactID; }
            set { SetPropertyValue<Guid>("VersionOwnerContactID", ref fVersionOwnerContactID, value); }
        }
        Guid fVersionOwnerCompanyID;
        public Guid VersionOwnerCompanyID
        {
            get { return fVersionOwnerCompanyID; }
            set { SetPropertyValue<Guid>("VersionOwnerCompanyID", ref fVersionOwnerCompanyID, value); }
        }
        DateTime fVersionUpdated;
        public DateTime VersionUpdated
        {
            get { return fVersionUpdated; }
            set { SetPropertyValue<DateTime>("VersionUpdated", ref fVersionUpdated, value); }
        }
    }

}
