//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"X_UsageAudit")]
    public partial class UsageAudit : XPLiteObject
    {
        Guid fAuditID;
        [Key(true)]
        public Guid AuditID
        {
            get { return fAuditID; }
            set { SetPropertyValue<Guid>("AuditID", ref fAuditID, value); }
        }
        DictionaryUsageAuditType fUsageAuditTypeID;
        [Association(@"UsageAuditReferencesDictionaryUsageAuditType")]
        public DictionaryUsageAuditType UsageAuditTypeID
        {
            get { return fUsageAuditTypeID; }
            set { SetPropertyValue<DictionaryUsageAuditType>("UsageAuditTypeID", ref fUsageAuditTypeID, value); }
        }
        string fEntitySystemType;
        [Size(255)]
        public string EntitySystemType
        {
            get { return fEntitySystemType; }
            set { SetPropertyValue<string>("EntitySystemType", ref fEntitySystemType, value); }
        }
        string fEntityID;
        [Size(50)]
        public string EntityID
        {
            get { return fEntityID; }
            set { SetPropertyValue<string>("EntityID", ref fEntityID, value); }
        }
        string fAction;
        [Size(SizeAttribute.Unlimited)]
        public string Action
        {
            get { return fAction; }
            set { SetPropertyValue<string>("Action", ref fAction, value); }
        }
        DateTime fAudited;
        public DateTime Audited
        {
            get { return fAudited; }
            set { SetPropertyValue<DateTime>("Audited", ref fAudited, value); }
        }
        Guid fContactID;
        public Guid ContactID
        {
            get { return fContactID; }
            set { SetPropertyValue<Guid>("ContactID", ref fContactID, value); }
        }
    }

}
