//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace XODB.Module.BusinessObjects.XODB
{

    [Persistent(@"Q_WarehouseModel")]
    public partial class WarehouseModel : XPLiteObject
    {
        Guid fWarehouseModelID;
        [Key(true)]
        public Guid WarehouseModelID
        {
            get { return fWarehouseModelID; }
            set { SetPropertyValue<Guid>("WarehouseModelID", ref fWarehouseModelID, value); }
        }
        DictionaryModel fModelID;
        [Association(@"WarehouseModelReferencesX_DictionaryModel")]
        public DictionaryModel ModelID
        {
            get { return fModelID; }
            set { SetPropertyValue<DictionaryModel>("ModelID", ref fModelID, value); }
        }
        Warehouse fWarehouseID;
        [Association(@"WarehouseModelReferencesWarehouse")]
        public Warehouse WarehouseID
        {
            get { return fWarehouseID; }
            set { SetPropertyValue<Warehouse>("WarehouseID", ref fWarehouseID, value); }
        }
        decimal fIssueCost;
        public decimal IssueCost
        {
            get { return fIssueCost; }
            set { SetPropertyValue<decimal>("IssueCost", ref fIssueCost, value); }
        }
        decimal fQuantityOnOrder;
        public decimal QuantityOnOrder
        {
            get { return fQuantityOnOrder; }
            set { SetPropertyValue<decimal>("QuantityOnOrder", ref fQuantityOnOrder, value); }
        }
        decimal fQuantityInStock;
        public decimal QuantityInStock
        {
            get { return fQuantityInStock; }
            set { SetPropertyValue<decimal>("QuantityInStock", ref fQuantityInStock, value); }
        }
        decimal fQuantityOnHold;
        public decimal QuantityOnHold
        {
            get { return fQuantityOnHold; }
            set { SetPropertyValue<decimal>("QuantityOnHold", ref fQuantityOnHold, value); }
        }
        decimal fQuantityReOrderLevel;
        public decimal QuantityReOrderLevel
        {
            get { return fQuantityReOrderLevel; }
            set { SetPropertyValue<decimal>("QuantityReOrderLevel", ref fQuantityReOrderLevel, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>("Version", ref fVersion, value); }
        }
        Guid fVersionAntecedentID;
        public Guid VersionAntecedentID
        {
            get { return fVersionAntecedentID; }
            set { SetPropertyValue<Guid>("VersionAntecedentID", ref fVersionAntecedentID, value); }
        }
        int fVersionCertainty;
        public int VersionCertainty
        {
            get { return fVersionCertainty; }
            set { SetPropertyValue<int>("VersionCertainty", ref fVersionCertainty, value); }
        }
        Guid fVersionWorkflowInstanceID;
        public Guid VersionWorkflowInstanceID
        {
            get { return fVersionWorkflowInstanceID; }
            set { SetPropertyValue<Guid>("VersionWorkflowInstanceID", ref fVersionWorkflowInstanceID, value); }
        }
        Guid fVersionUpdatedBy;
        public Guid VersionUpdatedBy
        {
            get { return fVersionUpdatedBy; }
            set { SetPropertyValue<Guid>("VersionUpdatedBy", ref fVersionUpdatedBy, value); }
        }
        Guid fVersionDeletedBy;
        public Guid VersionDeletedBy
        {
            get { return fVersionDeletedBy; }
            set { SetPropertyValue<Guid>("VersionDeletedBy", ref fVersionDeletedBy, value); }
        }
        Guid fVersionOwnerContactID;
        public Guid VersionOwnerContactID
        {
            get { return fVersionOwnerContactID; }
            set { SetPropertyValue<Guid>("VersionOwnerContactID", ref fVersionOwnerContactID, value); }
        }
        Guid fVersionOwnerCompanyID;
        public Guid VersionOwnerCompanyID
        {
            get { return fVersionOwnerCompanyID; }
            set { SetPropertyValue<Guid>("VersionOwnerCompanyID", ref fVersionOwnerCompanyID, value); }
        }
        DateTime fVersionUpdated;
        public DateTime VersionUpdated
        {
            get { return fVersionUpdated; }
            set { SetPropertyValue<DateTime>("VersionUpdated", ref fVersionUpdated, value); }
        }
        [Association(@"WarehouseModelSupplierReferencesQ_WarehouseModel", typeof(WarehouseModelSupplier))]
        public XPCollection<WarehouseModelSupplier> WarehouseModelSuppliers { get { return GetCollection<WarehouseModelSupplier>("WarehouseModelSuppliers"); } }
        [Association(@"ProjectPlanTaskModelReferencesQ_WarehouseModel", typeof(ProjectPlanTaskModel))]
        public XPCollection<ProjectPlanTaskModel> ProjectPlanTaskModels { get { return GetCollection<ProjectPlanTaskModel>("ProjectPlanTaskModels"); } }
    }

}
