//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XODB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.X_CompanyAddress = new HashSet<CompanyAddress>();
            this.X_CompanyRelation = new HashSet<CompanyRelation>();
            this.X_CompanyRelation1 = new HashSet<CompanyRelation>();
            this.X_Experience = new HashSet<Experience>();
            this.X_SecurityBlacklist = new HashSet<SecurityBlacklist>();
            this.X_SecurityBlacklist1 = new HashSet<SecurityBlacklist>();
            this.X_SecurityWhitelist = new HashSet<SecurityWhitelist>();
            this.X_SecurityWhitelist1 = new HashSet<SecurityWhitelist>();
        }
    
        public System.Guid CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CountryID { get; set; }
        public Nullable<System.Guid> PrimaryContactID { get; set; }
        public string Comment { get; set; }
        public int Version { get; set; }
        public Nullable<System.Guid> VersionAntecedentID { get; set; }
        public Nullable<int> VersionCertainty { get; set; }
        public Nullable<System.Guid> VersionWorkflowInstanceID { get; set; }
        public Nullable<System.Guid> VersionUpdatedBy { get; set; }
        public Nullable<System.Guid> VersionDeletedBy { get; set; }
        public Nullable<System.Guid> VersionOwnerContactID { get; set; }
        public Nullable<System.Guid> VersionOwnerCompanyID { get; set; }
        public Nullable<System.DateTime> VersionUpdated { get; set; }
    
        public virtual Contact X_Contact { get; set; }
        public virtual ICollection<CompanyAddress> X_CompanyAddress { get; set; }
        public virtual ICollection<CompanyRelation> X_CompanyRelation { get; set; }
        public virtual ICollection<CompanyRelation> X_CompanyRelation1 { get; set; }
        public virtual ICollection<Experience> X_Experience { get; set; }
        public virtual ICollection<SecurityBlacklist> X_SecurityBlacklist { get; set; }
        public virtual ICollection<SecurityBlacklist> X_SecurityBlacklist1 { get; set; }
        public virtual ICollection<SecurityWhitelist> X_SecurityWhitelist { get; set; }
        public virtual ICollection<SecurityWhitelist> X_SecurityWhitelist1 { get; set; }
    }
}
