//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XODB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpatialContainer : DbContext
    {
        public SpatialContainer()
            : base("name=SpatialContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Location> Locations { get; set; }
        public DbSet<LocationAlias> LocationAlias { get; set; }
        public DbSet<LocationData> LocationDatas { get; set; }
        public DbSet<LocationHistories> LocationHistory { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<ProvinceData> ProvinceDatas { get; set; }
        public DbSet<ProvinceRelation> ProvinceRelations { get; set; }
    }
}
