//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XODB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_DictionaryWorkTypeClass
    {
        public System.Guid WorkTypeClassID { get; set; }
        public string StandardWorkTypeClassName { get; set; }
        public string CoalWorkTypeClassName { get; set; }
        public string GoldWorkTypeClassName { get; set; }
        public string CustomWorkTypeClassName { get; set; }
        public string Description { get; set; }
        public string FullDescription { get; set; }
        public byte[] Thumbnail { get; set; }
        public Nullable<System.Guid> OriginalFileDataID { get; set; }
        public int Version { get; set; }
        public Nullable<System.Guid> VersionAntecedentID { get; set; }
        public Nullable<int> VersionCertainty { get; set; }
        public Nullable<System.Guid> VersionWorkflowInstanceID { get; set; }
        public Nullable<System.Guid> VersionUpdatedBy { get; set; }
        public Nullable<System.Guid> VersionDeletedBy { get; set; }
        public Nullable<System.Guid> VersionOwnerContactID { get; set; }
        public Nullable<System.Guid> VersionOwnerCompanyID { get; set; }
        public Nullable<System.DateTime> VersionUpdated { get; set; }
    }
}
