//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XODB.Import.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_DictionarySampleCategory
    {
        public X_DictionarySampleCategory()
        {
            this.X_AssayGroupStandardTestResult = new HashSet<X_AssayGroupStandardTestResult>();
            this.X_Sample = new HashSet<X_Sample>();
        }
    
        public System.Guid SampleCategoryID { get; set; }
        public string StandardSampleCategoryName { get; set; }
        public string CoalSampleCategoryName { get; set; }
        public string GoldSampleCategoryName { get; set; }
        public string CustomSampleCategoryName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<X_AssayGroupStandardTestResult> X_AssayGroupStandardTestResult { get; set; }
        public virtual ICollection<X_Sample> X_Sample { get; set; }
    }
}
