//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XODB.Import.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_DictionarySampleState
    {
        public X_DictionarySampleState()
        {
            this.X_AssayGroupStandardTestResult = new HashSet<X_AssayGroupStandardTestResult>();
            this.X_Sample = new HashSet<X_Sample>();
        }
    
        public System.Guid SampleStateID { get; set; }
        public string StandardSampleStateName { get; set; }
        public string CoalSampleStateName { get; set; }
        public string GoldSampleStateName { get; set; }
        public string CustomSampleStateName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<X_AssayGroupStandardTestResult> X_AssayGroupStandardTestResult { get; set; }
        public virtual ICollection<X_Sample> X_Sample { get; set; }
    }
}
