//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XODB.Import.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_GeophysicsMetadata
    {
        public X_GeophysicsMetadata()
        {
            this.X_GeophysicsData = new HashSet<X_GeophysicsData>();
        }
    
        public System.Guid GeophysicsMetadataID { get; set; }
        public System.Guid GeophysicsID { get; set; }
        public Nullable<System.Guid> ParameterID { get; set; }
        public string Mnemonic { get; set; }
        public string Unit { get; set; }
        public string Data { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Format { get; set; }
        public int Version { get; set; }
        public Nullable<System.Guid> VersionAntecedentID { get; set; }
        public Nullable<int> VersionCertainty { get; set; }
        public Nullable<System.Guid> VersionWorkflowInstanceID { get; set; }
        public Nullable<System.Guid> VersionUpdatedBy { get; set; }
        public Nullable<System.Guid> VersionDeletedBy { get; set; }
        public Nullable<System.Guid> VersionOwnerContactID { get; set; }
        public Nullable<System.Guid> VersionOwnerCompanyID { get; set; }
        public Nullable<System.DateTime> VersionUpdated { get; set; }
    
        public virtual X_Geophysics X_Geophysics { get; set; }
        public virtual ICollection<X_GeophysicsData> X_GeophysicsData { get; set; }
        public virtual X_Geophysics_Parameter X_Parameter { get; set; }
    }
}
