//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XODB.Import.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_Survey
    {
        public System.Guid SurveyID { get; set; }
        public System.Guid HeaderID { get; set; }
        public decimal Depth { get; set; }
        public Nullable<decimal> Dip { get; set; }
        public Nullable<decimal> MagneticDip { get; set; }
        public Nullable<bool> MagnetAffected { get; set; }
        public Nullable<decimal> OriginalAzimuth { get; set; }
        public Nullable<decimal> CorrectedAzimuth { get; set; }
        public Nullable<decimal> Gravity { get; set; }
        public Nullable<System.Guid> InstrumentModelID { get; set; }
        public string InstrumentAssetID { get; set; }
        public Nullable<System.DateTime> Surveyed { get; set; }
        public Nullable<System.Guid> SurveyContactID { get; set; }
        public Nullable<System.Guid> SurveyCompanyID { get; set; }
        public int Version { get; set; }
        public Nullable<System.Guid> VersionAntecedentID { get; set; }
        public Nullable<int> VersionCertainty { get; set; }
        public Nullable<System.Guid> VersionWorkflowInstanceID { get; set; }
        public Nullable<System.Guid> VersionUpdatedBy { get; set; }
        public Nullable<System.Guid> VersionDeletedBy { get; set; }
        public Nullable<System.Guid> VersionOwnerContactID { get; set; }
        public Nullable<System.Guid> VersionOwnerCompanyID { get; set; }
        public Nullable<System.DateTime> VersionUpdated { get; set; }
    
        public virtual X_Header X_Header { get; set; }
    }
}
