//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XODB.Import.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XODBImportCollarEntities : DbContext
    {
        public XODBImportCollarEntities()
            : base("name=XODBImportCollarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<X_DictionaryDataStatus> X_DictionaryDataStatus { get; set; }
        public DbSet<X_DictionaryHoleStatus> X_DictionaryHoleStatus { get; set; }
        public DbSet<X_DictionaryHoleType> X_DictionaryHoleType { get; set; }
        public DbSet<X_Header> X_Header { get; set; }
        public DbSet<X_HeaderRelation> X_HeaderRelation { get; set; }
        public DbSet<X_Survey> X_Survey { get; set; }
        public DbSet<X_Lithology> X_Lithology { get; set; }
        public DbSet<X_Geophysics> X_Geophysics { get; set; }
        public DbSet<X_GeophysicsData> X_GeophysicsData { get; set; }
        public DbSet<X_GeophysicsMetadata> X_GeophysicsMetadata { get; set; }
        public DbSet<X_Geophysics_Parameter> X_Geophysics_Parameter { get; set; }
    }
}
